### PR TITLE
COFF i960

### PR DESCRIPTION
**Pull request by mumbel**
COFF structs can be different based on the f_magic.  This PR implements the COFF for i960

(see https://github.com/NationalSecurityAgency/ghidra/commit/ca21388e65dee7b6b1287c00bf01c153b9b80cd4 and #1336)

### CODE REVIEW

**Comment by mumbel** [comment]
@ryanmkurtz   Just a quick attempt.  Any thoughts on this approach or suggestions on better approach given the current class structure.  Parsing seemed to go okay with this; however .text was not located correctly so something is still off

**Comment by ryanmkurtz** [comment]
I think the ideal design would be to make the variable components pluggable, similar to how we do the relocation handlers.  I'd have to think more about what that would look like though.  Second to that would be centralizing all of the logic that chooses what structure to use, like what is done in `CoffSectionHeaderFactory`.  That factory could be made more generic to handle more than just section header variations.

**Comment by mumbel** [comment]
so then for example `CoffSymbolAuxFactory` would have `CoffSymbolAuxFactory getHandler`
and then Processors i960 would have

**Comment by ryanmkurtz** [comment]
Is every one of those classes you listed a differently sized structure than what we currently have?

**Comment by mumbel** [comment]
Yeah, they're all padded out to 24 vs 18

**Comment by ryanmkurtz** [comment]
It may make the most sense for you to provide your own `I960_CoffLoader` alongside your processor that extends `CoffLoader` .  You could also extend the current structures to add the extra functionality you need (if necessary).  If done correctly, you may be able to pass along your custom structures up to the real `CoffLoader` and rely on it for most of the work.  We might have to change things about the `CoffLoader` to make this work, like making some private methods protected if you need to override them.

**Comment by ryanmkurtz** [comment]
You would probably have to start the overriding chain with `CoffFileHeader`, so it could use `I960_CoffSectionHeader` and `I960_CoffSymbol`.  If we did it this way, the fix I put in the other day wouldn't have been necessary...you would have been able to control the section size.

This "feels" right, but it might be a lot of work.

**Comment by mumbel** [comment]
https://github.com/mumbel/ghidra_i960/tree/coff

Still need to add the logic for the handler factory in ghidra core.  no rush and don't make a priority, but if you get a chance, this looking like the right way forward (also if you see any awful java or suggestions there please share)?

**Comment by ryanmkurtz** [comment]
Yes, that is basically had in mind.  I was also thinking that if you made your own `I960_CoffLoader` that extends `CoffLoader`, you wouldn't need to change much about `CoffLoader` (other than maybe making some private methods protected so you could override them).  Your .opinion file could reference your new version of the loader.  That way all of your i960 stuff is totally self-contained and it wouldn't be necessary to sprinkle references to it in core Ghidra.

**Comment by mumbel** [comment]
Nah, I can close and reopen if I come back to it. Its blocked by the module pr anyways and I figured out how tool pcodetest without this

**Pull request closed without merging**
