### PR TITLE
Correct PE rich header write method

### PR DESCRIPTION
**Pull request by xiaoyinl**
IMAGE_DANS_SIGNATURE should be XOR'ed with the mask.

### CODE REVIEW

**Comment by ryanmkurtz** [comment]
Were you using this `write()` method?  Seems to be unused in the codebase at the moment.

**Comment by xiaoyinl** [comment]
> Were you using this `write()` method? Seems to be unused in the codebase at the moment.

No. I just happened to notice this bug while researching for the root cause of #4514.

**Comment by ryanmkurtz** [comment]
Ok.  Would you mind briefly sharing how you knew that was the correct thing to do (will save me some research time)?

**Comment by xiaoyinl** [comment]
@ryanmkurtz Sure. In another file, RichTable.java, it scans for the DanS magic number by xor'ing every dword with the mask: Line 84 `(dw ^ mask) == RichHeader.IMAGE_DANS_SIGNATURE`

https://github.com/NationalSecurityAgency/ghidra/blob/62be7b1dc50c866eb94888bfef8a4bbb3a7ad26d/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/pe/RichTable.java#L79-L89

You can also verify this by opening any Windows PE files compiled by VS (e.g. https://msdl.microsoft.com/download/symbols/kernelbase.dll/8D5BD3DA379000/kernelbase.dll), and look at the DWORD values at 0x80 (the masked magic number) and 0x84 (the mask). If you XOR them, you get 'DanS' (0x536e6144)

**Comment by xiaoyinl** [comment]
Here is a write-up on the Rich Header: https://www.virusbulletin.com/virusbulletin/2020/01/vb2019-paper-rich-headers-leveraging-mysterious-artifact-pe-format/

**Comment by ryanmkurtz** [comment]
Thanks!

**Pull request merged**
