### PR TITLE
Include cspec docs in build

### LINKED ISSUE #1856: Build cspec documentation for Decompiler
**Describe the bug**
`cspec` documentation files exist in `Ghidra/Features/Decompiler/src/main/doc/` yet are not built alongside its siblings in the `build.gradle` script for the Decompiler

**Expected behavior**
The docs are built. Looks like they may have just been left out of the `buildDecompilerDocumentationPdfs` and `buildDecompilerDocumentationHtml` tasks

**Environment (please complete the following information):**
 - OS: Windows
 - Java Version: 11.0.7
 - Ghidra Version: 9.1.2

**Additional context**
#472

### PR DESCRIPTION
**Pull request by rchildre3**
* put docs into zip/docs/languages
* Frontpage.css: remove errant tilde character
* Mostly copying the layout of the sleigh docs
* Adjust xsl include locations to reflect the locations in the Debian
  and Ubuntu `docbook-xsl` package
* Commit generated html into GhidraDocs/ directory, as per convention

Fixes #1856

### CODE REVIEW

**Comment by ghidra1** [comment]
The ability to build this under Windows and Mac OS X is not readily available.  This is why it has not been incorporated into the standard build

**Comment by virtuald** [comment]
If you used a Java XSLT processor, that would make it usable under Windows/OSX? Maybe the [first google result for 'gradle xslt plugin'](https://github.com/eerohele/saxon-gradle)?

... I don't have any idea what is actually required, just making a suggestion.

**Comment by rchildre3** [comment]
I agree with @virtuald, I think that the entire `bash` subprocess call can be replaced with a few library calls, however I was not trying to re-architect the entire docs build process in this Merge Request.  I simply want the `cspec` docs to be built and distributed with the upcoming `9.2` release.

**Comment by rchildre3** [comment]
Is this still under consideration? Is there anything that can be added/removed/changed to be upstreamed?

**Pull request closed without merging**
