### PR TITLE
spelling of 'descendant' in identifiers, error messages, and comments

### PR DESCRIPTION
**Pull request by hippietrail**

### CODE REVIEW

**Review by ryanmkurtz — CHANGES_REQUESTED** [review]
Some of your corrections change it to `descendent`.  `descendant` seems to be more correct as both noun as adjective, at least in the brief research I just did.

**Comment by hippietrail** [comment]
> Some of your corrections change it to `descendent`. `descendant` seems to be more correct as both noun as adjective, at least in the brief research I just did.

Argh! Sorry about that. First I found an identifier with the first 's' missing then I did a search to find the others. I noticed that some ended in -ent instead of -ant and thought I fixed all of those too but indeed I did not.

**Comment by hippietrail** [comment]
Git has defeated me yet again. I found more occurrences of these misspellings but I haven't been able to figure out how to amend or squash these commits to make the PR nice and clean.

**Comment by ryanmkurtz** [comment]
Do you have your eclipse environment set up?  I think it's pretty easy to do this sort of thing from Eclipse.

**Comment by hippietrail** [comment]
> Do you have your eclipse environment set up? I think it's pretty easy to do this sort of thing from Eclipse.

I think I just squashed it! Let me know if it's good now. Apologies for the drama.

**Comment by ryanmkurtz** [comment]
Thanks, i merged it internally but it won't make it's way to github until tomorrow.

**Review by byt3n33dl3 — COMMENTED** [review]
# 'Descendent' / Master

**Pull request merged**
