### PR TITLE
Sleigh x86 improvements

### PR DESCRIPTION
**Pull request by Boyan-MILANOV**
This PR contains 2 bug fixes ~and 1 improvement~ to the `x86` sleigh specification. Since the changes are very easy to review I have packed everything in a single PR. Each change has its own commit.

- fix the constructor for `addr64` that uses 32-bit immediate: it was parsing the immediate as unsigned instead of signed (`imm32` instead of `simm32`)
- fix mistakes in the constructors for the `NOP` instruction which were causing `XCHG R8D, EAX` and `XCHG R8W, AX` to be erroneously decoded as `NOP`
- ~add support for lifting the `SHUFPD` instruction~

The issues were found while using [Maat](https://github.com/trailofbits/maat) which uses sleigh to lift and emulate instructions. I didn't find related issues on the Ghidra repo so I'm opening this PR standalone.

### CODE REVIEW

**Comment by GhidorahRex** [comment]
I'll take a look at the `addr64` constructor and NOP instruction changes, but we already have a `SHUFPD` implementation coming to the language soon (and several other instructions). These changes look good though, thanks for the submission!

**Comment by mumbel** [comment]
fixes #4310

**Comment by GhidorahRex** [comment]
We're almost ready to accept this, could you remove the SHUFPD commit from the PR?

**Comment by Boyan-MILANOV** [comment]
Done.

**Pull request merged**
