### PR TITLE
Store original hostname for new projects

### PR DESCRIPTION
**Pull request by peoplesmeat**
Addresses https://github.com/NationalSecurityAgency/ghidra/issues/4924

The net effect of this change is that Ghidra will store in it's .prp file the hostname the user entered, rather then the canonical name that was discovered for the IP that was associated with the hostname that the user entered. If there are users who expect this behaviour, they will encounter altered behaviour. Ghidra will still lookup the canonical name when using `RepositoryManager.getRMIClient` but the value in the prp file will be the original hostname the user entered.

I left the checks `InetNameLookup.getCanonicalHostName(host);` in ClientUtil to ensure that the hostname that is entered can be resolved. 

I tested and verified this change with a ghidra server in running in AWS.

### CODE REVIEW

**Comment by ghidra1** [comment]
Have you verified cached object behavior?  Need to ensure that concurrent connections from same client using either hostname, alias or IP address share a common RepositoryServerHandle to avoid re-authentication.  I believe the intent of transforming to a canonical name was to achieve this.  The key may be to preserve the original name for configuration retention (project.prp) but not for cached RepositoryServerHandles.

**Comment by peoplesmeat** [comment]
Ok, I updated this PR to maintain the original behaviour for RepositoryServerHandle with regard to hostname. 

The new addition is a field in `ServerInfo` which can maintain the "original hostname" as entered by a user and before canonicalization. In this case the `ProjectFileManager` will write the original name using `updatePropertiesFile` which maintains the hostname through to the prp file. This is only used in writing the project file and also in the `ProjectInfoDialog`

**Comment by ghidra1** [comment]
I would like to address this along with the SNI Proxy use case raised by PR #3396 , so I need to spend more time researching this before proceeding.

**Comment by ghidra1** [comment]
Desired behavior has been added to master branch and should get pushed next week. Thanks for the PR but we chose to work in along with some other changes.

**Pull request closed without merging**
