### PR TITLE
Change "our nation" to "the United States of America"

### PR DESCRIPTION
**Pull request by sylveon**
Many GitHub users (such as me) do not live in the USA, so it feels more appropriate to name the country explicitely because America isn't their nation.

### CODE REVIEW

**Comment by OothecaPickle** [comment]
seems fine imo as it's written from the point of view of the NSA, a US government agency.

**Comment by ctubbsii** [comment]
I can see it both ways. Perhaps some rephrasing would be helpful.

**Comment by notacatkiller** [comment]
Why not 'Murica?

**Comment by endrin** [comment]
The proposed change is kinda controversial. What if they gonna accept applications only from US? Then the wording should be something like "..._if you are an United States citizen,_ ... and would like to develop this, and
other cybersecurity tools, for NSA to help protect our nation..."

**Comment by jsoref** [comment]
Some change is necessary, this change is sufficient. The reason a change is necessary is that `our nation` qualifies `its allies`. A simpler change (which I'm not endorsing) would be `its nation`.

Given that `NSA` is abbreviated, I think `the USA` would be more in line with the sentence.

**Comment by sylveon** [comment]
@endrin That's true, [NSA only accepts American citizens](https://www.intelligencecareers.gov/nsa/nsafaq.html). In which case it makes total sense to use "our nation" provided "if you are an United States citizen" is present.

**Comment by NonCreature0714** [comment]
There is only one NSA. It only has one nation it protects which is “ours.” I think saying “help NSA protect the United States of America” is like saying “I’m a huge Dallas Cowboys American Football fan.” It’s unnecessarily specific.

**Comment by afturner** [comment]
This is an interesting conversation that I think may actually run a bit deeper than we are giving it credit; however, it's pretty irrelevant when you look at the sentence from the point of view of grammar.

> If you are interested in projects like this and would like to develop this, and other cybersecurity tools, for NSA to help protect our nation and its allies, consider applying for a career with us.

Removing redundancies:

> If you are interested ... and would like to develop this, and other cybersecurity tools ... consider applying for a career with us.

You'll notice that this is clearly written from the perspective of someone working AT the NSA (see: "us.") Whether or not you think it's appropriate in the context of open source is irrelevant, especially if you only propose to change the word "our." 

This is a release by an entity, with a disclaimer from a member of that entity, written from the perspective of that entity, referring to itself and the country it resides in, directed towards people eligible to work for the entity (ie; people of that country)... well it seems that "our" and "us" is totally acceptable. 

Finally:

> Many GitHub users (such as me) do not live in the USA, so it feels more appropriate to name the country explicitely because America isn't their nation.

Doesn't really make sense to me. Of course many people aren't from the USA. (1) they can't work at the NSA; (2) "our" and "us" isn't directly referring to the reader, though it can be argued that "our" is meant to be inclusive; (3) if you want to name the country explicitly, then "us" becomes vague.

So I guess what I'm saying is that at best this isn't a reasonable PR as it currently stands, and at worst, is a pointless issue to be talking about -- considering it takes longer to analyze a binary with Ghidra than it took me to write this, so there's definitely some code to be worked on ;)  

ps; I, too, am in favor of the 'Murica alternative.

**Comment by nsadeveloper789** [comment]
We're splitting hairs here, but we do really like the suggestion @endrin made. I'll close this and apply that edit.

**Pull request closed without merging**
