### PR TITLE
Bump yajsw to stable (from beta)

### PR DESCRIPTION
**Pull request by oliv3r**
This commit bumps yajsw to a stable version, instead of a beta version. While here, cleanup some whitespaces errors.

### CODE REVIEW

**Comment by ryanmkurtz** [comment]
Duplicate of #4092.

**Comment by oliv3r** [comment]
@ryanmkurtz while I agree it's a duplicate; not that this one is a big more complete, in updating _all_ referenes (including some docs) and b) has a boyscout commit you might want to keep.

If attribution is a concern, I can rebase my patch uppon #4092 however.

**Comment by ryanmkurtz** [comment]
Typically yajsw would be upgraded internally since the code changes are trivial but the required multiplatform testing is quite rigorous.  I kept #4092 open to give the contributor credit for initiating the starting point of the process, but only when I am ready to spend the day testing the various server startup modes on Linux, macOS, and Linux.  Also, keeping the change set minimal is preferred to adding whitespace cleanup which obscures the real changes and makes it harder to review.  This is mentioned in our [CONTRIBUTING.md](https://github.com/NationalSecurityAgency/ghidra/blob/master/CONTRIBUTING.md) document.

**Comment by ryanmkurtz** [comment]
I was also expecting the top-level directory bug I mention in the Server's build.gradle file to have been fixed with the newest version of yajsw.  Was that not an issue for you in your testing?

**Comment by oliv3r** [comment]
I did keep the whitespace cleanup minimal, as I only commited the changed to the files I touched upon (my editor/git client actually fixed those due to default settings). I completely agree with avoiding big white-space diffs over the whole code base; but is the intend ultimately not to clean it up entirely?

As for the pathing fix, I kept it initially as was, and all of that worked fine. Only after seeing the duplicate, I figured I must have been wrong ;)

So I'll let #4092 'deal' with that ;)

BTW, I'm more then happy to keep this one closed, and let all discussions be resolved there. Consider this MR a reference point for potentially missing updates if you will, once that branch is merged, we should have a zero diff here.

Thanks for your reply!

**Pull request closed without merging**
