### PR TITLE
solves issue #2334, also add a lot of defines for DT_FLAGS_1 that wer…

### PR DESCRIPTION
**Pull request by Jegeva**
…e missing to detect for PIE DYNs, so might as well have them

 issue #2334

### CODE REVIEW

**Comment by ghidra1** [comment]
My initial feeling is that the approach taken is incorrect but this will take more time for me to evaluate the original issue.  At first glance your change would appear to allocate fake externals in the EXTERNAL block for all symbols when `canExecute` is true.  This should only be done when a real memory address is not established (`address == Address.NO_ADDRESS`).   The EXTERNAL block is intended to be used only for those symbols not accounted for within the GOT/PLT for which relocations may reference.

**Comment by ghidra1** [comment]
The real issue is how we process the PLTGOT and migrating symbols into the External space (not EXTERNAL block).  The External space is used to identify Imports associated with the PLT.   I did notice that we did not properly handle the DT_JMPREL relocation table processing which plays a role in this.  I am currently working to fix this issues you have observed with #2334 .  The use of DT_FLAGS_1 is not the solution to this problem.

**Comment by Jegeva** [comment]
Sure, i am not familiar enough with the elf parsing codebase (far from it, tbh i installed eclipse and just debugged through the code until i found a point where right before it removed the symbols) to pretend that my approach is the correct one. Just so you know the way i did it (testing for an executable, even a relocatable one (which was the reason of the DF_FLAGS_1) end up creating the correct external references and the blocks in the library correctly point towards the correct symbol in the library. Just reject the proposed merge rq and give me a headsup in the issue if you manage to fix the parsing of JMPREL

**Comment by ghidra1** [comment]
Fix has been pushed to master if you would like to try it.  I am going to close this pull request.

**Pull request closed without merging**
