### PR TITLE
Implement Lzcnt zero test rule in the decompiler

### PR DESCRIPTION
**Pull request by chrisps**
This adds a new rule that detects whether the result of a call to the PPC or Arm leading zero count userop is shifted to the left by log2(input_operand_size*CHAR_BIT) and replaces the shift with an INT_NOTEQUAL of the lzcnt operand and zero. 
This is a very common pattern on PPC and ARM, so this should improve codegen for those platforms. It doesn't seem ideal to directly check the userop names, but that seemed to be the only approach in this case. 

This rule does NOT eliminate the orphaned lzcnt calls when their outputs have zero descendants, that seemed like something for a different pull request. Ideally something would be added to the userop definitions in the pspecs that would indicate a userop is a pure function, allowing it to be killed off when its result is unused.

### CODE REVIEW

**Comment by chrisps** [comment]
This look okay? Anything in particular I need to do to get this merged?

**Comment by chrisps** [comment]
Hey, I don't mean to be rude, but it's been nearly two years and I haven't had any input on why this won't be accepted.

**Comment by ryanmkurtz** [comment]
Sorry, we acknowledge that things have fallen through the cracks but we are taking measures to improve.  I will label this accordingly and we will do our best to address it soon.

**Comment by caheckman** [comment]
We are planning to add a dedicated p-code operator for "leading zero count" operations and then creating a decompiler rule based on that to solve this issue.

**Comment by Pokechu22** [comment]
@caheckman Have you seen #2810? It does just that.

**Comment by alexmaloteaux** [comment]
@caheckman @ryanmkurtz  would it be possible to take a new look at #2810, it does exactly what proposed and just works perfectly. On some arm32 toolchains this pattern is extremly frequent.

Best  Regards

**Pull request closed without merging**
