### PR TITLE
Fix #2176 removing both backslash from path

### LINKED ISSUE #2176: LaunchSupport expected 2 to 4 arguments but got 1
I have installed ghidra and jdk version 11.0.8 (the only version 11 I can find), both in the "Program Files" folder on a Win 10 VM in VMWare Pro.

When I run java -version, I get:
java version "11.0.8" 2020-07-14 LTS 
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode) 

Here is my system path variable string:
C:\Program Files\bin;C:\cygwin64\bin;C:\Program Files\Java\jdk-11.0.8\bin\
I even added the java bin path to its own new line, just in case.

This is my error message:
C:\Program Files\ghidra_9.1.2_PUBLIC>ghidraRun.bat 
LaunchSupport expected 2 to 4 arguments but got 1 
LaunchSupport expected 2 to 4 arguments but got 1 
LaunchSupport expected 2 to 4 arguments but got 1 

Failed to find a supported JDK.  Please refer to the Ghidra Installation Guide's Troubleshooting section. 

I have deleted and re-downloaded and installed ghidra but I still get the same message. Any ideas what else I can do here?
Thanks,
Ryan

### PR DESCRIPTION
**Pull request by M9k**
As suggested #3121 squashed and rebased on brach Ghidra_10.0.
Thanks to @topia for fix a missing \\, thanks @ryanmkurtz for the support

### CODE REVIEW

**Review by Wall-AF — COMMENTED** [review]
With the initial removal of the `\` in the `set` commands and the removal of the `\` in four `"%INSTALL_DIR%\"` uses, you are handing a path into the `LaunchSupport` class with a trailing `..` instead of `..\`.  As the current use of this doesn't "add" anything to it, it'll work, however that intention should be clarified within the class and the script.

**Comment by topia** [comment]
> With the initial removal of the `\` in the `set` commands and the removal of the `\` in four `"%INSTALL_DIR%\"` uses, you are handing a path into the `LaunchSupport` class with a trailing `..` instead of `..\`. As the current use of this doesn't "add" anything to it, it'll work, however that intention should be clarified within the class and the script.

I don't know the history about this, but other platforms don't add trailing slashes.
https://github.com/NationalSecurityAgency/ghidra/blob/5fa3ab488d1d2ba973af735afb6e2a42ac89010f/Ghidra/RuntimeScripts/Linux/support/launch.sh#L93

**Comment by Wall-AF** [comment]
> 
> 
> > With the initial removal of the `\` in the `set` commands and the removal of the `\` in four `"%INSTALL_DIR%\"` uses, you are handing a path into the `LaunchSupport` class with a trailing `..` instead of `..\`. As the current use of this doesn't "add" anything to it, it'll work, however that intention should be clarified within the class and the script.
> 
> I don't know the history about this, but other platforms don't add trailing slashes.
> 
> https://github.com/NationalSecurityAgency/ghidra/blob/5fa3ab488d1d2ba973af735afb6e2a42ac89010f/Ghidra/RuntimeScripts/Linux/support/launch.sh#L93

By asking the user to add the path separator, prior to adding their relative path, there's a risk of writing to the root of the drive `iff` no path is passed (possibly causing errors if the user doesn't have `write` permission) as opposed to writing relative to the CWD.

Just an observation!

**Comment by topia** [comment]
I see.
In this case, cmd.exe sets full path (with trailing backslash) to `%SUPPORT_DIR%`, so I think there is no such risk.
https://github.com/NationalSecurityAgency/ghidra/blob/c98e6fe3bbd5e7efd06606891a1d95a4246d4eb6/Ghidra/RuntimeScripts/Windows/support/launch.bat#L34-L39

**Comment by Wall-AF** [comment]
> 
> 
> I see.
> In this case, cmd.exe sets full path (with trailing backslash) to `%SUPPORT_DIR%`, so I think there is no such risk.
> 
> https://github.com/NationalSecurityAgency/ghidra/blob/c98e6fe3bbd5e7efd06606891a1d95a4246d4eb6/Ghidra/RuntimeScripts/Windows/support/launch.bat#L34-L39

Hovever `..` is added indicating the directory above should be used!

**Comment by topia** [comment]
Ah, I didn't catch your message. I'm sorry.

**Comment by topia** [comment]
This script will install as `(ghidra-install-root)/support/launch.bat` and call from ghidraRun.bat, so it should be harmless for the usual case.
If someone put this script to another directory, or [remove `(ghidra-installl-root)/Ghidra` directory](https://github.com/NationalSecurityAgency/ghidra/blob/5fa3ab488d1d2ba973af735afb6e2a42ac89010f/Ghidra/RuntimeScripts/Windows/support/launch.bat#L71), the script may use the outside of install directory.

**Review by ryanmkurtz — APPROVED** [review]

**Pull request closed without merging**
