### PR TITLE
Adding IIDs from Windows SDK 10.0.22621.0.

### PR DESCRIPTION
**Pull request by americusmaximus**
Following up on conversation in [Adding missing ids from ddraw.h and d3d.h](https://github.com/NationalSecurityAgency/ghidra/pull/5958) I created a quick [tool](https://github.com/americusmaximus/GIIDX) to extract the id values and corresponding names from the .idl files.

Adding extracted ids from Windows SDK 10.0.22621.0.

The ids include interfaces, enums, structs, classes, and coclasses.

### CODE REVIEW

**Comment by ryanmkurtz** [comment]
Sorry for the delay...I'm looking to incorporate this now.  I made a simple script to validate your file against our old one, and I noticed that you have some duplicate UUIDs.  For example:

```
00000148-0000-0000-C000-000000000046 IAddrExclusionControl
00000148-0000-0000-C000-000000000046 IComBinding
```

Do you know why this is happening?

**Comment by ryanmkurtz** [comment]
Here's the full output of my script, which lists duplicate keys and mismatches from your file to the one in our repo:

```
HelloWorldScript.java> Running...
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 00000148-0000-0000-C000-000000000046 -> IAddrExclusionControl / IComBinding
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 000214FE-0000-0000-C000-000000000046 -> IRemoteComputer / IShellCommandUI
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 0DF2C7E5-3435-11D0-81D0-00C04FD85AB4 -> INNTPCallback / INNTPTransport
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 0DF2C7E6-3435-11D0-81D0-00C04FD85AB4 -> INNTPCallback / INNTPTransport
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 1CFF0050-6FDD-11D0-9328-00A0C90DCAA9 -> IActiveScriptParseProcedureOld / IActiveScriptParseProcedureOld32
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 3050F2F1-98B5-11CF-BB82-00AA00BDCE0B -> IHTMLViewFilter / IViewFilter
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 3050F2F4-98B5-11CF-BB82-00AA00BDCE0B -> IHTMLViewFilterSite / IViewFilterSite
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 310AFA62-0575-11D2-9CA9-0060B0EC3D39 -> IDSOControl / IXMLDSOControl
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 36116642-D713-4B97-9B83-7484A9D00433 -> IFileDialogControlEvents / IID_IFileDialogControlEvents_MFC
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 3D577EFF-4CEE-11E6-B535-001BDC06AB3B -> IRadialController2 / IRadialControllerIndependentInputSourceInterop
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 3D8B0590-F691-11D2-8EA9-006097DF5BD4 -> IAsyncOperation / IDataObjectAsyncCapability
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 5C4EE536-6A98-4B86-A170-587013D6FD4B -> IHolographicSpaceInterop / ISpatialInteractionManagerInterop
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 625E2DF8-6392-4CF0-9AD1-3CFA5F17775C -> IPortableDevice / IPortableDeviceConnector
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 71EE5B20-FB04-11D1-B3A8-00A0C911E8B2 -> IActiveScriptParseProcedure2 / IActiveScriptParseProcedure2_32
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 7C0FFAB2-CD84-11D0-949A-00A0C91110ED -> DataSourceListener / IDataSourceListener
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 7C0FFAB3-CD84-11D0-949A-00A0C91110ED -> DataSource / IDataSource
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 7D96BC74-9B54-4CA1-AD3A-979C3D44DDAC -> IPrintWorkflowObjectModelTargetPackage / IPrintWorkflowXpsObjectModelTargetPackageNative
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: 973510DB-7D7F-452B-8975-74A85828D354 -> IFileDialogEvents / IID_IFileDialogEvents_MFC
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: AA5B6A80-B834-11D0-932F-00A0C90DCAA9 -> IActiveScriptParseProcedure / IActiveScriptParseProcedure32
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: BB1A2AE2-A4F9-11CF-8F20-00805F2CD064 -> IActiveScriptParse / IActiveScriptParse32
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: E2AE82B7-229D-4428-B3D2-500000000006 -> _IMAPI_FEATURE_PAGE_TYPE / _IMAPI_FORMAT2_DATA_MEDIA_STATE
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: E2AE82B7-229D-4428-B3D2-500000000006 -> _IMAPI_FORMAT2_DATA_MEDIA_STATE / _IMAPI_FORMAT2_DATA_WRITE_ACTION
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: E2AE82B7-229D-4428-B3D2-500000000006 -> _IMAPI_FORMAT2_DATA_WRITE_ACTION / _IMAPI_MODE_PAGE_TYPE
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: E2AE82B7-229D-4428-B3D2-500000000006 -> _IMAPI_MODE_PAGE_TYPE / _IMAPI_PROFILE_TYPE
HelloWorldScript.java> Duplicate IID in Downloads/iids.txt: ED8C108D-4349-11D2-91A4-00C04F7969E8 -> IXMLHTTPRequest / IXMLHttpRequest
HelloWorldScript.java> Mismatch on IID BB1A2AE2-A4F9-11CF-8F20-00805F2CD064 -> IActiveScriptParse / IActiveScriptParse32
HelloWorldScript.java> Mismatch on IID 1CFF0050-6FDD-11D0-9328-00A0C90DCAA9 -> IActiveScriptParseProcedureOld / IActiveScriptParseProcedureOld32
HelloWorldScript.java> Mismatch on IID 3D8B0590-F691-11D2-8EA9-006097DF5BD4 -> IAsyncOperation / IDataObjectAsyncCapability
HelloWorldScript.java> Mismatch on IID 71EE5B20-FB04-11D1-B3A8-00A0C911E8B2 -> IActiveScriptParseProcedure2 / IActiveScriptParseProcedure2_32
HelloWorldScript.java> Mismatch on IID ED8C108D-4349-11D2-91A4-00C04F7969E8 -> IXMLHTTPRequest / IXMLHttpRequest
HelloWorldScript.java> Mismatch on IID 0DF2C7E5-3435-11D0-81D0-00C04FD85AB4 -> INNTPCallback / INNTPTransport
HelloWorldScript.java> Mismatch on IID 3050F2F1-98B5-11CF-BB82-00AA00BDCE0B -> IHTMLViewFilter / IViewFilter
HelloWorldScript.java> Mismatch on IID 3050F2F4-98B5-11CF-BB82-00AA00BDCE0B -> IHTMLViewFilterSite / IViewFilterSite
HelloWorldScript.java> Mismatch on IID 310AFA62-0575-11D2-9CA9-0060B0EC3D39 -> IDSOControl / IXMLDSOControl
HelloWorldScript.java> Mismatch on IID AA5B6A80-B834-11D0-932F-00A0C90DCAA9 -> IActiveScriptParseProcedure / IActiveScriptParseProcedure32
HelloWorldScript.java> Done!
HelloWorldScript.java> Finished!
```

**Comment by americusmaximus** [comment]
Hello,

Please see response below.

**Duplicates**

```
`00000148-0000-0000-C000-000000000046 -> IAddrExclusionControl / IComBinding`

File `objidlbase.Idl` on lines 1398-1403 defines the id as `interface IAddrExclusionControl : IUnknown`.
```

```
`000214FE-0000-0000-C000-000000000046 -> IRemoteComputer / IShellCommandUI`

File `ShObjIdl_core.idl` on lines 4329-4334 defines the id as `interface IRemoteComputer : IUnknown`.
```

```
`0DF2C7E5-3435-11D0-81D0-00C04FD85AB4 -> INNTPCallback / INNTPTransport`

Multiple definitions.
File `imnxport.idl` on lines 81-82 defines the id as `IID_INNTPCallback`,
at the same time in the same file on lines 2730-2734 the definition is `interface INNTPTransport : IInternetTransport`.

Personally, I would go with `INNTPTransport`.
```

```
`0DF2C7E6-3435-11D0-81D0-00C04FD85AB4 -> INNTPCallback / INNTPTransport`

Multiple definitions.
File `imnxport.idl` on lines 85-86 defines the id as `IID_INNTPTransport`,
at the same time in the same file on lines 2503-508 the definition is `interface INNTPCallback : ITransportCallback`.

Personally, I would go with `INNTPCallback`.
```

```
`1CFF0050-6FDD-11D0-9328-00A0C90DCAA9 -> IActiveScriptParseProcedureOld / IActiveScriptParseProcedureOld32`

File `ActivScp.Idl` on lines 89-90 and 692-697 defines the id as `interface IActiveScriptParseProcedureOld32 : IUnknown`.
It looks like `IActiveScriptParseProcedureOld` is a legacy name.
```

```
`3050F2F1-98B5-11CF-BB82-00AA00BDCE0B -> IHTMLViewFilter / IViewFilter`

File `ocmm.Idl` on lines 40-46 defines the id as `interface IViewFilter : IUnknown`
```
```

`3050F2F4-98B5-11CF-BB82-00AA00BDCE0B -> IHTMLViewFilterSite / IViewFilterSite`

File `ocmm.Idl` on lines 69-75 defines the id as `interface IViewFilterSite : IUnknown`
```

`310AFA62-0575-11D2-9CA9-0060B0EC3D39 -> IDSOControl / IXMLDSOControl`

```
This one is trully interesting. It is defined in multiple places:
1. File `XmlDso.Idl` on lines 31-42 as `interface IXMLDSOControl : IDispatch`.
2. File `MsXml2.Idl` on lines 1616-1627 as `interface IDSOControl : IDispatch`.

Do you have an opinion which one shall be picked?
```

```
`36116642-D713-4B97-9B83-7484A9D00433 -> IFileDialogControlEvents / IID_IFileDialogControlEvents_MFC`

File `ShObjIdl.idl` on lines 847-852 defines the id as `interface IFileDialogControlEvents : IUnknown`.
```

```
`3D577EFF-4CEE-11E6-B535-001BDC06AB3B -> IRadialController2 / IRadialControllerIndependentInputSourceInterop`

This one is defined in two places, it looks like one is relevant for classic Windows, and another for WinRT:
1. File `RadialControllerInterop.idl` on lines 46-51: `interface IRadialControllerIndependentInputSourceInterop : IInspectable`. 
2. File `windows.ui.input.idl` on lines 1006-1009: `interface IRadialController2 : IInspectable`.

Do you have an opinion which one shall be picked?
```

```
`3D8B0590-F691-11D2-8EA9-006097DF5BD4 -> IAsyncOperation / IDataObjectAsyncCapability`

File `shldisp.idl` on lines 1093-1094 defines the id as `interface IDataObjectAsyncCapability : IUnknown`.
```

```
`5C4EE536-6A98-4B86-A170-587013D6FD4B -> IHolographicSpaceInterop / ISpatialInteractionManagerInterop`

Multiple definitions.
File `HolographicSpaceInterop.idl` on lines 17-20 defines the id as `interface IHolographicSpaceInterop : IInspectable`,
at the same time in file `SpatialInteractionManagerInterop.idl` on lines 17-20 the definition is `interface ISpatialInteractionManagerInterop : IInspectable`.

Do you have an opinion which one shall be picked?
```

```
`625E2DF8-6392-4CF0-9AD1-3CFA5F17775C -> IPortableDevice / IPortableDeviceConnector`

Multiple definitions.
File `PortableDeviceApi.idl` on lines 95-101 defines the id as `interface IPortableDevice : IUnknown`,
at the same time in file `PortableDeviceConnectApi.idl` on lines 63-69 the definition is `interface IPortableDeviceConnector : IUnknown`.

Do you have an opinion which one shall be picked?
```

```
`71EE5B20-FB04-11D1-B3A8-00A0C911E8B2 -> IActiveScriptParseProcedure2 / IActiveScriptParseProcedure2_32`

File `ActivScp.Idl` on lines 101-102 and 792-797 defines the id as `interface IActiveScriptParseProcedure2_32 : IActiveScriptParseProcedure32`.

It looks like `IActiveScriptParseProcedure2` is a legacy name.
```

```
`7C0FFAB2-CD84-11D0-949A-00A0C91110ED -> DataSourceListener / IDataSourceListener`

File `msdatsrc.idl` on lines 65-71 defines the id as `interface DataSourceListener : IUnknown`.
However, line 67 has comment `IDataSourceListener`.

Personally, I would go with `DataSourceListener`.
```

```
`7C0FFAB3-CD84-11D0-949A-00A0C91110ED -> DataSource / IDataSource`

File `msdatsrc.idl` on lines 81-86 defines the id as `interface DataSource : IUnknown`.
However, line 79 has comment `IDataSource`.

Personally, I would go with `DataSource`.
```
```

`7D96BC74-9B54-4CA1-AD3A-979C3D44DDAC -> IPrintWorkflowObjectModelTargetPackage / IPrintWorkflowXpsObjectModelTargetPackageNative`

Multiple definitions.
File `windows.graphics.printing.workflow.native.idl` on lines 70-75 defines the id as `interface IPrintWorkflowXpsObjectModelTargetPackageNative : IUnknown`,
at the same time in file `windows.graphics.printing.workflow.idl` on lines 501-504 the definition is `interface IPrintWorkflowObjectModelTargetPackage : IInspectable`.

Do you have an opinion which one shall be picked?
```

```
`973510DB-7D7F-452B-8975-74A85828D354 -> IFileDialogEvents / IID_IFileDialogEvents_MFC`

File `ShObjIdl_core.idl` on lines 5830-5835 defines the id as `interface IFileDialogEvents : IUnknown`.
```

```
`AA5B6A80-B834-11D0-932F-00A0C90DCAA9 -> IActiveScriptParseProcedure / IActiveScriptParseProcedure32`

File `ActivScp.Idl` on lines 95-96 and 741-746 defines the id as `interface IActiveScriptParseProcedure32 : IUnknown`.

It looks like `IActiveScriptParseProcedure` is a legacy name.
```
```

`BB1A2AE2-A4F9-11CF-8F20-00805F2CD064 -> IActiveScriptParse / IActiveScriptParse32`

File `ActivScp.Idl` on lines 75-76 and 608-613 defines the id as `interface IActiveScriptParse32 : IUnknown`.

It looks like `IActiveScriptParse` is a legacy name.
```

```
`E2AE82B7-229D-4428-B3D2-500000000006 -> _IMAPI_FEATURE_PAGE_TYPE / _IMAPI_FORMAT2_DATA_MEDIA_STATE`
`E2AE82B7-229D-4428-B3D2-500000000006 -> _IMAPI_FORMAT2_DATA_MEDIA_STATE / _IMAPI_FORMAT2_DATA_WRITE_ACTION`
`E2AE82B7-229D-4428-B3D2-500000000006 -> _IMAPI_FORMAT2_DATA_WRITE_ACTION / _IMAPI_MODE_PAGE_TYPE`
`E2AE82B7-229D-4428-B3D2-500000000006 -> _IMAPI_MODE_PAGE_TYPE / _IMAPI_PROFILE_TYPE`

This is a very interesting and puzzling case.

File `imapi2.idl` contains multiple definitions of enums attributed with the same ids, see the following lines:
1. 136-142
2. 162-168
3. 223-229
4. 272-278
5. 298-304

Do you have an opinion on what has be done here? My suggestion is to omit this one.
```

```
`ED8C108D-4349-11D2-91A4-00C04F7969E8 -> IXMLHTTPRequest / IXMLHttpRequest`

This one has multiple definitions:
1. File `MsXml2.Idl` on lines 1643-1652: `interface IXMLHTTPRequest : IDispatch`.
2. File `MsXml6.Idl` on lines 1567-1577: `interface IXMLHTTPRequest : IDispatch`.
3. File `XmlDom.Idl` on lines 1177-1186: `interface IXMLHttpRequest : IDispatch`.

Based on the comments and context around - all of them are the same thing. Do you have an opinion which one shall be picked?
```

**Mismatches**

`BB1A2AE2-A4F9-11CF-8F20-00805F2CD064 -> IActiveScriptParse / IActiveScriptParse32`
`1CFF0050-6FDD-11D0-9328-00A0C90DCAA9 -> IActiveScriptParseProcedureOld / IActiveScriptParseProcedureOld32`
`3D8B0590-F691-11D2-8EA9-006097DF5BD4 -> IAsyncOperation / IDataObjectAsyncCapability`
`71EE5B20-FB04-11D1-B3A8-00A0C911E8B2 -> IActiveScriptParseProcedure2 / IActiveScriptParseProcedure2_32`
`ED8C108D-4349-11D2-91A4-00C04F7969E8 -> IXMLHTTPRequest / IXMLHttpRequest`
`0DF2C7E5-3435-11D0-81D0-00C04FD85AB4 -> INNTPCallback / INNTPTransport`
`3050F2F1-98B5-11CF-BB82-00AA00BDCE0B -> IHTMLViewFilter / IViewFilter`
`3050F2F4-98B5-11CF-BB82-00AA00BDCE0B -> IHTMLViewFilterSite / IViewFilterSite`
`310AFA62-0575-11D2-9CA9-0060B0EC3D39 -> IDSOControl / IXMLDSOControl`
`AA5B6A80-B834-11D0-932F-00A0C90DCAA9 -> IActiveScriptParseProcedure / IActiveScriptParseProcedure32`

I believe all mismatches are covered in my responses above.

Happy to update my pull request with some guidance on what ids shall be picked in case of conflicts.

**Comment by ryanmkurtz** [comment]
Thanks for digging in to this.  I guess in general we should go with the more detailed version.  For example:
```
BB1A2AE2-A4F9-11CF-8F20-00805F2CD064 -> IActiveScriptParse / IActiveScriptParse32
```
I'd go with the 32 one.

For
```
310AFA62-0575-11D2-9CA9-0060B0EC3D39 -> IDSOControl / IXMLDSOControl
```
I'd go with the XML one...provides more detail.  You can use your judgement for the others, with this type of logic breaking the ties if you aren't sure.

**Comment by americusmaximus** [comment]
The pull request is updated. Thank you.

**Comment by ryanmkurtz** [comment]
Thank you, I will not be able to revisit this until next week, but I'll let you know if there are any issues then.

**Pull request merged**
