### PR TITLE
Fix display issue for status message (VersionControlCheckOutAction)

### PR DESCRIPTION
**Pull request by sudofox**
Exclusive checkout message doesn't render correctly in the status-bar. Moving it onto the same line with a space and wrapping the message in parenthesis (as is already done for the multiple-failed message) will make it display correctly in both the statusbar and the logger.

Screenshot from 2020-11-29 22-49-26

Screenshot from 2020-11-29 22-58-45

### CODE REVIEW

**Comment by dragonmacher** [comment]
We allow clients that use message dialogs to make messages more readable by adding newlines.    Our 'log viewer' is a simple UI that allows users to see the logs without opening the log file in their favorite text editor.   This simplistic log viewer was designed to show multi-line messages, which is especially useful view viewing exceptions.

As far as the Front End's status area is concerned, the only mistake I can see in the image you posted is that the newline character was dropped completely and not replaced with a space character.  I'm assuming the is the default behavior of Java's JLabel.   We should update the status area to preemptively swap newline characters with spaces before setting the text.

**Comment by sudofox** [comment]
Sounds good to me, where would be the best place to make that change?

**Comment by dragonmacher** [comment]
The change needs to go into `LogPanel.messageLogged()`.

**Comment by sudofox** [comment]
I only made the change for the label and not the tooltip, so the character is replaced inline with the label.setText call.

**Comment by dragonmacher** [comment]
The change is good.   I will add some extra fixin's and get it merged in.

**Review by dragonmacher — APPROVED** [review]

**Comment by sudofox** [comment]
Closing: Though GitHub doesn't show it, this was added in via merge commit https://github.com/NationalSecurityAgency/ghidra/commit/f69546e508fd9ac9225354bf22869b27498da10a

**Pull request closed without merging**
