### PR TITLE
Minor text corrections

### PR DESCRIPTION
**Pull request by TheJambo**

### CODE REVIEW

**Comment by SamboyCoding** [comment]
"your contributing to this project" is valid grammar and shouldn't be changed.

**Comment by Hacksawfred3232** [comment]
Double checked with other people who knows English a lot better than me, "Your contribution to this project" is correct. Voted down incorrect answer.

**Comment by recvfrom** [comment]
I think "contributing", as used in the original text, is acceptable - I think it's a Gerund (see https://guinlist.wordpress.com/2014/01/12/70-gerunds/, section 2).  I'm definitely not an English language expert, though.

"Your contribution to this project" also works, I think, although sometimes the wording associated with text conveying legal implications is worded certain ways for reasons unknown to me (IANAL).

As implemented in the pull request, changing to "contributions" is not correct, because it would require the following "does" to be changed to "do".

**Comment by TheJambo** [comment]
Thanks @recvfrom @Hacksawfred3232, fixed my own issue there.

**Comment by nsadeveloper789** [comment]
Looks good. Thanks for the help!

**Pull request merged**
