### PR TITLE
Updated DemanglerGnu

### LINKED ISSUE #1195: Segfault in gnu_demangler
**Describe the bug**
The linux64 `demangler_gnu` program segfaults when given specific symbols.

**To Reproduce**
Run the following code.

```
echo "_ZSt7forwardIOZNK18CompoundTagVariant3getEvEUlRT_E_EOS1_RNSt16remove_referenceIS1_E4typeE" | /opt/ghidra/GPL/DemanglerGnu/os/linux64/demangler_gnu
```

**Expected behavior**
The program should output something like
```
CompoundTagVariant::get() const::{lambda(auto:1&)#1}&& std::forward<CompoundTagVariant::get() const::{lambda(auto:1&)#1}&&>(std::remove_reference<CompoundTagVariant::get() const::{lambda(auto:1&)#1}&&>::type&)
```
instead of segfaulting. (Calculated at http://demangler.com/)

**Environment (please complete the following information):**
 - OS: Linux 5.3.7-arch1-2-ARCH x86_64 GNU/Linux
 - Java Version: 11
 - Ghidra Version: 9.1

### LINKED ISSUE #1451: demangler_gnu crashes with BAD_ACCESS in  d_unqualified_name function
**Describe the bug**

There is a memory access violation (BAD_ACCESS) in the d_unqualified_name function [1]  of demangler_gnu, as demonstrated with  the string "_ZN11951592242730AnimationOverlayHandlerImplD18446744073709551616Ev" . This leads to a segmentation fault when launching the demangler_gnu process. 

[1] https://github.com/NationalSecurityAgency/ghidra/blob/6ae0c1ce239932882b7e4577d76ebd7d23779a09/GPL/DemanglerGnu/src/demangler_gnu/c/cp-demangle.c#L1486

**To Reproduce**
lldb  ./GPL/DemanglerGnu/os/osx64/demangler_gnu _ZN11951592242730AnimationOverlayHandlerImplD18446744073709551616Ev

(lldb) target create "./GPL/DemanglerGnu/os/osx64/demangler_gnu"
Current executable set to './GPL/DemanglerGnu/os/osx64/demangler_gnu' (x86_64).
(lldb) settings set -- target.run-args  "_ZN11951592242730AnimationOverlayHandlerImplD18446744073709551616Ev"
(lldb) r
Process 46162 launched: '/Users/marc/Downloads/ghidra_9.1.1_PUBLIC/GPL/DemanglerGnu/os/osx64/demangler_gnu' (x86_64)
Process 46162 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x7ffea228f89d)
    frame #0: 0x0000000100009eab demangler_gnu`d_unqualified_name + 571
demangler_gnu`d_unqualified_name:
->  0x100009eab <+571>: movsx  ecx, byte ptr [rax]
    0x100009eae <+574>: cmp    ecx, 0x42
    0x100009eb1 <+577>: jne    0x100009ec8               ; <+600>
    0x100009eb7 <+583>: mov    rdi, qword ptr [rbp - 0x10]
Target 0: (demangler_gnu) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x7ffea228f89d)
  * frame #0: 0x0000000100009eab demangler_gnu`d_unqualified_name + 571
    frame #1: 0x000000010000a09f demangler_gnu`d_prefix + 255
    frame #2: 0x0000000100009986 demangler_gnu`d_nested_name + 166
    frame #3: 0x000000010000901f demangler_gnu`d_name + 79
    frame #4: 0x00000001000023d1 demangler_gnu`d_encoding + 81
    frame #5: 0x0000000100002279 demangler_gnu`cplus_demangle_mangled_name + 201
    frame #6: 0x000000010000826c demangler_gnu`d_demangle_callback + 556
    frame #7: 0x0000000100007f91 demangler_gnu`d_demangle + 65
    frame #8: 0x0000000100007f3f demangler_gnu`cplus_demangle_v3 + 31
    frame #9: 0x00000001000103cc demangler_gnu`cplus_demangle + 188
    frame #10: 0x0000000100011b42 demangler_gnu`demangle_it + 130
    frame #11: 0x000000010001164b demangler_gnu`main + 507
    frame #12: 0x00007fff6b67c3d5 libdyld.dylib`start + 1
    frame #13: 0x00007fff6b67c3d5 libdyld.dylib`start + 1
(lldb) register read rax
     rax = 0x00007ffea228f89d

**Expected behavior**
No crash, return proper error return code. 

**Environment (please complete the following information):**
 - OS: [e.g. macOS 10.14.6]
 - Java Version: [13.0.2]
 - Ghidra Version: [ 9.1.1]

**Additional context**
In the long run the Ghidra default demangler could be implemented in a language which does not allow memory faults when using attacker created mangled symbols.

### LINKED ISSUE #1454: Infinite recursion in demangler_gnu
**Describe the bug**
Applying the reproducer from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78252 (2016) leads to a stack recursion. 

**To Reproduce**

 lldb ./GPL/DemanglerGnu/os/osx64/demangler_gnu "_ZSt7forwardIRZN8abcdefgh6abcdef15abcde_abcdefghi12_GLOBAL__N_116abcdefAbcdefghijERSt6vectorIPNS1_16abcde_abcdefghij24AbdefAbcdefghijAbcdefghiESaIS7_EEmdEUlRT_E3_EOSB_RNSt16abcdef_abcdefghiISB_E4typeE" 
[..]
thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x7ffeef3fff18)
    frame #0: 0x00000001000052ce demangler_gnu`d_print_comp + 94
demangler_gnu`d_print_comp:
->  0x1000052ce <+94>:  call   0x100007d10               ; d_print_saw_error
    0x1000052d3 <+99>:  cmp    eax, 0x0
    0x1000052d6 <+102>: je     0x1000052e1               ; <+113>
    0x1000052dc <+108>: jmp    0x100007b21               ; <+10417>
Target 0: (demangler_gnu) stopped.

[...] 
   frame #11125: 0x00000001000054c7 demangler_gnu`d_print_comp + 599
    frame #11126: 0x0000000100006301 demangler_gnu`d_print_comp + 4241
    frame #11127: 0x00000001000069d6 demangler_gnu`d_print_comp + 5990
    frame #11128: 0x0000000100007a29 demangler_gnu`d_print_comp + 10169
    frame #11129: 0x00000001000054c7 demangler_gnu`d_print_comp + 599
    frame #11130: 0x0000000100006301 demangler_gnu`d_print_comp + 4241
    frame #11131: 0x00000001000069d6 demangler_gnu`d_print_comp + 5990
    frame #11132: 0x0000000100007a29 demangler_gnu`d_print_comp + 10169
    frame #11133: 0x00000001000054c7 demangler_gnu`d_print_comp + 599
    frame #11134: 0x0000000100006301 demangler_gnu`d_print_comp + 4241
    frame #11135: 0x00000001000064fb demangler_gnu`d_print_comp + 4747
    frame #11136: 0x00000001000058fd demangler_gnu`d_print_comp + 1677
    frame #11137: 0x000000010000516a demangler_gnu`cplus_demangle_print_callback + 106
    frame #11138: 0x000000010000832b demangler_gnu`d_demangle_callback + 747
    frame #11139: 0x0000000100007f91 demangler_gnu`d_demangle + 65
    frame #11140: 0x0000000100007f3f demangler_gnu`cplus_demangle_v3 + 31
    frame #11141: 0x00000001000103cc demangler_gnu`cplus_demangle + 188
    frame #11142: 0x0000000100011b42 demangler_gnu`demangle_it + 130
    frame #11143: 0x000000010001164b demangler_gnu`main + 507
    frame #11144: 0x00007fff6b67c3d5 libdyld.dylib`start + 1

**Expected behavior**
Process input with proper return value 

**Environment (please complete the following information):**
 - OS: [e.g. macOS 10.14.6]
 - Java Version: [e.g. 13.0.2]
 - Ghidra Version: [e.g. 9.1.1]

**Additional context**
The default demangler version with Ghidra seems out of date, a rebase to newer libiberty may reduce the attack surface.  The upstream version was fixed with https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=243568

### PR DESCRIPTION
**Pull request by astrelsky**
This also adds Rust and Dlang demangling support and does not remove support for the older mangling formats. Resolves #1454, resolves #1451 and resolves #1195

Please double check the IP headers for d-demangle.c and rust-demangle.c.

I initially started to rewrite it in Java but after a few hours in I said forget it. Felt like I was reinventing the wheel and it was just a waste of time.

### CODE REVIEW

**Comment by dragonmacher** [comment]
We are actually in the process of updating the GNU demangler.   We intend to build from binutils 2.33.1.   

Porting to Java would be interesting, but I think there is little value added by doing so, considering that the `c++filt` is open source.

**Comment by astrelsky** [comment]
> We are actually in the process of updating the GNU demangler. We intend to build from binutils 2.33.1.
> 
> Porting to Java would be interesting, but I think there is little value added by doing so, considering that the `c++filt` is open source.

I see. May you ensure that support for the older mangling styles (gnu, lucid, arm, hp and edg) are not removed? That is the reason I had gone ahead and done it myself. I'm also looking to do #1308 but will admit that due to my absent-mindedness programming in c can be a bit dangerous I guess.

**Comment by dragonmacher** [comment]
>  May you ensure that support for the older mangling styles (gnu, lucid, arm, hp and edg) are not removed?

I have not had time to fully parse the binutils change log.  Did they remove support for these?

> I'm also looking to do #1308 but will admit that due to my absent-mindedness programming in c can be a bit dangerous I guess. I'm essentially just looking to check for the -s or --format switch if the first part of the mangled name is -

It sound like the demangler has the tools to accomplish what you want here, but we do not provide a way to pass the correct swtiches.  If that is the case, then we would have to change our APIs to allow for this.  Do you believe any changes are needed to the `c++filt` to resolve this issue?

**Comment by dragonmacher** [comment]
I should also mention that our goal with updating the demangler is to modify as little as possible of their source code.   That being said, we can make modifications if they add significant value.  We have to weigh the trade-off of the added functionality vs. the weight of dragging changes across versions when we upgrade.

Significant functionality changes should be submitted directly to the binutils projects, which we would then get after they have updated.

**Comment by astrelsky** [comment]
> > May you ensure that support for the older mangling styles (gnu, lucid, arm, hp and edg) are not removed?
> 
> I have not had time to fully parse the binutils change log. Did they remove support for these?
> 
> > I'm also looking to do #1308 but will admit that due to my absent-mindedness programming in c can be a bit dangerous I guess. I'm essentially just looking to check for the -s or --format switch if the first part of the mangled name is -
> 
> It sound like the demangler has the tools to accomplish what you want here, but we do not provide a way to pass the correct swtiches. If that is the case, then we would have to change our APIs to allow for this. Do you believe any changes are needed to the `c++filt` to resolve this issue?

```
2018-12-22  Jason Merrill  <jason@redhat.com>

	Remove support for demangling GCC 2.x era mangling schemes.
	* cplus-dem.c: Remove cplus_mangle_opname, cplus_demangle_opname,
	internal_cplus_demangle, and all subroutines.
	(libiberty_demanglers): Remove entries for ancient GNU (pre-3.0),
	Lucid, ARM, HP, and EDG demangling styles.
	(cplus_demangle): Remove 'work' variable.  Don't call
	internal_cplus_demangle.
```

**Comment by dragonmacher** [comment]
I see.   We will have to evaluate whether we can keep that support.   I'm curious to know how significant are those changes.

**Comment by astrelsky** [comment]
> I see. We will have to evaluate whether we can keep that support. I'm curious to know how significant are those changes.

From what I gather they were just removing code that was no longer in use. All I did to keep it was re add the format names, the scheme array entries, copy in the v2 era functions and add the final check at the end.

Unfortunately losing support for the gnu format would mean any binary compiled with gcc2 or earlier would have their mangled labels unable to be demangled. The "only demangle known mangled names" option would no longer serve any purpose as that option just checks if it is gnu-v3 format.

**Comment by dragonmacher** [comment]
There seems to be roughly 3k lines of code removed that we would have to put back in order to support those older demangling styles.   That is a significant amount of code for us to have to maintain.

As I mentioned before, we are leaning towards including the **current** `c++filt` code.  Unfortunately for our users, this would mean more work for them when they needed to demangle older symbols.  Effectively, users would have to find or create their own demangler (or older version of `c++filt`) in order to process those symbols.   In that case, we hope to provide an easy way for users to plug-in their own demangler from scripting and from the UI.

It is a shame that support has been removed from binutils.  I would be curious to know why the code was removed and whether the maintainers would have any interest in restoring it.

**Comment by astrelsky** [comment]
> It is a shame that support has been removed from binutils. I would be curious to know why the code was removed and whether the maintainers would have any interest in restoring it.

It was code for the gcc v2 mangling scheme. The last release of gcc2 was in March 2001. It had remained unused internally since then and there is absolutely no reason for them to restore it.

All the relevant code is in `cplus-dem.c` from the end of the `internal_cplus_demangle` function to the end of the file. 4060 lines of code which is understandable.

What about splitting them?

**Comment by dragonmacher** [comment]
> It was code for the gcc v2 mangling scheme. The last release of gcc2 was in March 2001. It had remained unused internally since then and there is absolutely no reason for them to restore it.

If the maintainers are interested in forward engineering only, then it makes sense to me that they would not want to maintain the legacy code.  If, on the other hand, they realize that some customers use their tool to reverse engineer, or even debug, old binaries, then there is value in keeping the old code, I think.

> What about splitting them?

We are discussing the possibility of shipping 2 versions of the demangler: the new one and the older one.  We have to weigh the costs of updating the API to be able to use the older version as well as the security implications.

**Pull request closed without merging**
