### PR TITLE
#1268 Added the guidelines regarding binary file attachments into the bug report template

### PR DESCRIPTION
**Pull request by Ionut1994**
I have added the guidelines regarding binary file attachments from the CONTRIBUTING.md file into the bug report template as was suggested.

### CODE REVIEW

**Comment by ryanmkurtz** [comment]
It looks like you added the "Patch Submission tips," which does not seem appropriate for the bug report template.

**Comment by Ionut1994** [comment]
I couldn't find other relevant guidelines in the repository so I thought these were it. Do you know where can I find the necessary guidelines for this issue?

**Comment by ryanmkurtz** [comment]
As far as I know, there aren't any, which is why #1268 was created.  If you try to tackle this yourself, you are kind of just guessing at what the developers' policies are.  I'd recommend just letting them handle #1268.

**Comment by astrelsky** [comment]
The intent behind #1268 was to help make information regarding binary attachments in bug reports readily known. Such information would include whether the attachment contains any sort of malicious code, whether the reporter has the rights to distribute it and things of that nature.

**Comment by GhidorahRex** [comment]
We will take a look at the bug report template to develop and publish some policies on binary file attachments, but we won't be accepting this pull-request.

**Pull request closed without merging**
