### PR TITLE
Fix some uninitialized members in Decompiler

### PR DESCRIPTION
**Pull request by thestr4ng3r**
I was running the decompiler in a single process multiple times with the exact same input multiple times and got completely different outputs. After detecting (with valgrind) and fixing these issues, the output was fixed for my cases.

### CODE REVIEW

**Comment by thestr4ng3r** [comment]
ping

**Comment by caheckman** [comment]
All these variables are initialized in their class's reset() method. Is reset() not getting called in your situation?

**Comment by thestr4ng3r** [comment]
No it is not. I use a custom subclass of `SleighArchitecture` and call `allacts.getCurrent()->perform()`.

**Comment by caheckman** [comment]
Your code needs to call
`allacts.getCurrent()->reset();`
once per function decompilation, immediately prior to calling
`allacts.getCurrent()->perform(); `
This gives all actions and rules a chance to (re)initialize per-function state variables.  See
`DecompileAt::rawAction`
for example.
Closing this PR as the variables it sets are initialized in the respective actions' reset() method.

**Comment by thestr4ng3r** [comment]
I don't like this approach, but it works. Thanks.

**Pull request closed without merging**
