### PR TITLE
Use print() function in both Python 2 and Python 3 

### PR DESCRIPTION
**Pull request by cclauss**
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected n both Python 2 and Python 3.

### CODE REVIEW

**Comment by cclauss** [comment]
https://github.com/jython/jython3

**Comment by astrelsky** [comment]
Last commit by jeff5 about 2 years ago.
(https://github.com/jython/jython3/issues/36)[jython3 issue 36]

**Comment by ryanmkurtz** [comment]
Note that print() is a defined method in GhidraScript, so when you call it from a PythonScript, it's actually calling our defined Java method.

**Comment by cclauss** [comment]
Does that redirect happen even when `from __future__ import print_function` is used?

**Comment by ryanmkurtz** [comment]
I just tested this out and I was wrong, GhidraScript's print() method is not actually callable from our Jython environment, which was unexpected.  And it looks like you don't need to import anything to use the built-in print() function...Jython 2.7.1 already knows about it somehow.

**Comment by cclauss** [comment]
Try __print("A", "B")__ on Jython with and without the import as discussed at https://github.com/jython/book/pull/6#discussion_r284123254

**Comment by ryanmkurtz** [comment]
The import has no effect on `print("A", "B")` in our scripting environment.  It's just prints` ('A', 'B')` in both cases.

**Comment by cclauss** [comment]
Known bug https://bugs.jython.org/issue2007

**Comment by cclauss** [comment]
Closing... With 125 days left until Python 2 end of life, it is clear that an upgrade is not possible.

**Pull request closed without merging**
