### PR TITLE
Fixed CParser bitfields and function pointers.

### PR DESCRIPTION
**Pull request by astrelsky**
Bitfield types whose lengths are compiler specific are cloned to the parsers datatype manager prior to composite insertion. FunctionDataTypes are converter to a pointer prior to composite insertion.

### CODE REVIEW

**Comment by emteere** [comment]
Do you have a sample data definition?
It can be added to the JUNIT test for the CParser

**Comment by astrelsky** [comment]
> Do you have a sample string data definition that was not parsed before, but it now?
> It can be added to the JUNIT test for the CParser

The function definition one can be done fairly easily as it would just be a struct with a function pointer.

```
struct {
    void *(*functionPtr)(void*, char*);
} functionPointerTest;
```

The bit field one might be a bit difficult to test for as it depends on what data organization is available. This is what gave me some trouble with a compiler spec that has long_size set to 8.

```
struct {
    long bits:60;
    long bit:1;
} bitFieldTest;
```

**Comment by astrelsky** [comment]
@emteere I just noticed this morning that I made a mistake that cause a build failure. I believe I have fixed it this morning.

**Comment by ghidra1** [comment]
Could you please try the current master branch to see if it addresses you concerns.  When bitfield support was added provisions had been made to distinguish between declared bitsize and effective bitsize.  It was simply an incorrect restriction in the CParser Declaration class.  The intent is to preserve the original bitfield declaration and avoid mutating it.   The effective bitfield size will be clamped to the size of the base data type.

**Comment by astrelsky** [comment]
> Could you please try the current master branch to see if it addresses you concerns. When bitfield support was added provisions had been made to distinguish between declared bitsize and effective bitsize. It was simply an incorrect restriction in the CParser Declaration class. The intent is to preserve the original bitfield declaration and avoid mutating it. The effective bitfield size will be clamped to the size of the base data type.

So, if I have a long:52 as a bitfield does that mean it will automatically become long:32 or will it stay long:52?

**Comment by ghidra1** [comment]
They declaration would remain long:52 but would only occupy 32-bits within the composite (assuming a long size of 32-bits for the target data organization).

**Comment by ghidra1** [comment]
Take a look at the test I added: `StructureImplBigEndianBitFieldTest.testStructureBitFieldsA3()`

**Comment by astrelsky** [comment]
> They declaration would remain long:52 but would only occupy 32-bits within the composite (assuming a long size of 32-bits for the target data organization).

As long as it will remain long:52 and extend back to 52 bits when the target data organization has a 64 bit long then this can be closed. Assuming function pointers are no longer a problem.

**Comment by ghidra1** [comment]
Yes.  That is the intent of preserving the declared size

**Comment by ghidra1** [comment]
NOTE: Movement of composites containing bitfields works best for aligned composites, although changes in endianess may produce incorrect bitfield ordering since frequently an endianess `#ifdef` is used in source code to alter bitfield ordering (e.g., network protocol structures).  Also, movement of unaligned composites, which contain bitfields, in/out of datatype archives may have unintended consequences.

**Pull request closed without merging**
