### PR TITLE
[toolbar_item_manager] Fix NPE while calling method for windowManager

### LINKED ISSUE #1810: NPE while using buttons from toolbar of block in Function Graph
**Describe the bug**
You will get Null Pointer Exception if try to use buttons from toolbar of basic block in Function Graph (see stack trace below).

**To Reproduce**
1. Open Function Graph (you should have an opened program in a tool of course).
2. Press any button from toolbar of basic block (set color, view to fullscreen, combine vertices, see Fig. 1).

**Expected behavior**
Setting color or other action for the basic block without NPE.

**Screenshots**

> Fig. 1. Toolbar of basic block

**Attachments**
<details>
  <summary>Stack trace</summary>

```
ERROR (SwingExceptionHandler) Error: Uncaught Exception!  java.lang.NullPointerException
        at docking.menu.ToolBarItemManager.actionPerformed(ToolBarItemManager.java:116)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at docking.menu.MultipleActionDockingToolbarButton$PopupMouseListener.mouseReleased(MultipleActionDockingToolbarButton.java:345)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6397)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
        at ghidra.graph.viewer.event.mouse.VertexMouseInfo.forwardEvent(VertexMouseInfo.java:188)
        at ghidra.graph.viewer.event.mouse.VisualGraphEventForwardingGraphMousePlugin.mouseReleased(VisualGraphEventForwardingGraphMousePlugin.java:151)
        at ghidra.graph.viewer.event.mouse.VisualGraphPluggableGraphMouse.mouseReleased(VisualGraphPluggableGraphMouse.java:154)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6397)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</details>

**Environment (please complete the following information):**
 - Ghidra Version: bcb825fb029232175625bc85653ec0e810b1252e
- JVM Version: Oracle Corporation 11.0.6
- OS: Linux 5.6.6-arch1-1 amd64

**Additional context**
I found, that mistake was coded in 1d0340d83, I localized the error and created a PR.

### PR DESCRIPTION
**Pull request by saruman9**
A mistake was made in 1d0340d83. The commit was big, so I could not analyze it completely, accordingly, I could make mistakes in PR.

Fix #1810.

### CODE REVIEW

**Comment by saruman9** [comment]
Any review?

**Comment by ryanmkurtz** [comment]
COVID is still causing delays.  The reviews will come.

**Comment by saruman9** [comment]
Of course I understand. It’s just that other PRs have not been reviewed for a long time, even before COVID.

**Comment by ryanmkurtz** [comment]
Yea, some have definitely slipped by.  I would poke them again when you see that team activity has picked back up.

**Comment by dragonmacher** [comment]
We are digging into this a bit now.   The offending code has reach further back then just the file you updated.  There may be more changes required.

**Comment by saruman9** [comment]
Fixed by b7e6faf2dc235d05cbad7bef21d7e666f57677b2.

**Pull request closed without merging**
