### PR TITLE
Build PDB.exe using MSBuild instead of devenv

### PR DESCRIPTION
**Pull request by kant2002**
In addition to replacing just with MSBuild, I also pass
MSVC toolset using PlatformToolset property and Windows SDK using
WindowsTargetPlatformVersion property.

relates to #999

### CODE REVIEW

**Comment by kant2002** [comment]
I finally have time to start pushing code. This is not fully completed to satisfy me, but small piece which in my opinion make sense for you guys, and allow control of Windows SDK and VC Toolset using Gradle properties. /cc @ryanmkurtz

**Comment by kant2002** [comment]
Just want to ping @ryanmkurtz as a reminder

**Comment by ryanmkurtz** [comment]
We are currently in bug fix mode, focusing on getting the 9.1 beta ready for final release.  We will definitely get to this, but it will be for master/9.2.

**Comment by ryanmkurtz** [comment]
I am starting to take a deeper look at building with VS19.  I started by evaluating this pull request.  Did you test this change with VS17 or just VS19?  It only works on VS19 for me.

**Comment by kant2002** [comment]
I have build which working both with VS2017 and 2019 on Azure. I did not test locally, but  under assumption that msbuild on the path (from vcvars)

**Comment by ryanmkurtz** [comment]
Ok once you get your other pull request up we can probably close this one and work from that one, since it includes what's in here.

**Comment by kant2002** [comment]
@ryanmkurtz what specifically does not work for you with VS2017 ? I would like to move piece meal with VS changes, since I cannot install VS2017 right now and as such somewhat blind to the changes I made. I expect that `/p:PlatformToolset=${platformToolset} /p:WindowsTargetPlatformVersion=${MSVC_SDK_VERSION}` part **may not work** but not 100% sure. When I say it may not work, it mean that properties would not be passed to project properly. If so, I have solution to that problem [probably](https://stackoverflow.com/questions/45452145/how-to-set-platformtoolset-property-from-msbuild).

Also if #1039 land before I start changing search function for VS, we will not come into conflict, since it is location where change likely will land.

**Comment by ryanmkurtz** [comment]
@kant2002, since we have the requirement of being able to continue building with our existing VS17 environment, I think it would be most efficient if I add support for VS19 myself, and then when that is in and working (I have both environments installed), we can sync back up to add any additional support for your environment that you need.

**Comment by kant2002** [comment]
@ryanmkurtz for me only changes was in closed PR, since that time you move code a bit, but not much. I was just curios what was not working. Will wait for VS2019 support from you guys then.

**Comment by ryanmkurtz** [comment]
"Ghidra\Features\PDB\src\pdb\pdb.sln" (default target) (1) ->
"Ghidra\Features\PDB\src\pdb\pdb.vcxproj" (default target) (2) ->
(Link target) ->
  LINK : fatal error LNK1104: cannot open file 'MSVCRT.lib' [Ghidra\Features\PDB\src\pdb\pdb.vcxproj]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:06.66

> Task :PDB:win64PDBMake FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':PDB:win64PDBMake'.
> Process 'command 'cmd'' finished with non-zero exit value 1

**Comment by kant2002** [comment]
According to that [link](https://stackoverflow.com/questions/6228112/link-fatal-error-lnk1104-cannot-open-file-msvcrtd-lib) you probably should install "VC ++ 2017 version v141 Libs for Spectre".

**Comment by ryanmkurtz** [comment]
Why do you want to use MSBuild instead of devenv?  I should have opened with that.

**Comment by kant2002** [comment]
Reason why I think msbuild should be used, it's that way you can control platform toolsets and Windows SDK. For example that way somebody can use whatever Widnows SDK installed on their PC. With devenv it would be more hard to implement I think. 

Also it allow build Ghidra without VS installed. Definitely not priority for me, but think it would be +1 for that change.

**Comment by ryanmkurtz** [comment]
Ok thanks for the explanation.

**Comment by ryanmkurtz** [comment]
> According to that [link](https://stackoverflow.com/questions/6228112/link-fatal-error-lnk1104-cannot-open-file-msvcrtd-lib) you probably should install "VC ++ 2017 version v141 Libs for Spectre".

Useful link, thanks.  Since we don't want to change anything about our build environment at this time, I simply disabled Spectre mitigation in the vcxproj file and it built.

Can you please choose from one of the following options for how you'd like to proceed so you get credit for your contributions?

1. You manually add your VS installation search code from #730 into this pull-request (into vsconfig.gradle), and I can work from this branch.
2. You rebase #730 onto master, and I can work from that branch. 
3. I work from this branch, and you give me permission to copy what I want from #730.  You won't get commit-credit for any of that VS installation search code that I might copy and use though.  Not sure if you care about that.  You would get credit for this pull-request though.

**Comment by ryanmkurtz** [comment]
Actually, I'm going to go with choice 3, because I think I am going to locate VS via the `vswhere.exe` program.  So, no need for you to change anything about your pull-requests for now.

**Comment by ryanmkurtz** [comment]
Actually that spectre thing had nothing to do with your changes.

**Comment by kant2002** [comment]
I can make Spectre flag passed to msbuild so that thing can be controlled by Gradle later on. This seems to be potentially desired configuration option

**Comment by ryanmkurtz** [comment]
Ok, sounds good!  We'll want it off by default.

**Comment by ryanmkurtz** [comment]
When you get that in, I plan to accept this pull-request.  Once accepted, I am going to make some changes to use vshwere.exe to find the latest studio and just use that.

**Comment by ryanmkurtz** [comment]
I went ahead and merged this in.  I changed it slightly so you can define WindowsTargetPlatformVersion on the Gradle command line as a property.  If left undefined it will just use Visual Studio's default SDK. Anyone who wants to build for Windows 7 (like us) can set this Gradle property to "8.1".

Also, no need to make any changes for the Spectre mitigation.

**Comment by kant2002** [comment]
Thanks. Now will try to incorporate that change in my fork.

**Comment by ryanmkurtz** [comment]
Cool.  I'm currently working on #999 to get in support for VS19.

**Pull request merged**
