### PR TITLE
#1494: Fix incorrect handling of relocations for ARM BE8 binaries

### PR DESCRIPTION
**Pull request by WorksButNotTested**
Fix for #1494

### CODE REVIEW

**Comment by ghidra1** [comment]
Your change appears to target specific relocation types while others were left unchanged.  How did you go about identifying the relocation types which you utilize the instruction endianess flag?  You past comments indicated that data endianess and associated fixups were section specified (.data vs .text) but I don't see this reflected in your change.

**Comment by WorksButNotTested** [comment]
Please see section 4.9 of this article. https://static.docs.arm.com/ihi0044/g/aaelf32.pdf

In BE8, the instruction stream is little endian, whilst data accesses are big endian. Thus relocations that are patching instructions must be treated as little endian, whereas those targeting data must be treated as big endian. Different relocation types are used for each. The article linked lays which are used for each. The mention of .text and .data, was an over simplification.

I did put a link into the comments on the issue itself, but there's quite a lot of text in there, so easily missed.

Hope tis helps to clarify. Please advise if there's anything further.

**Comment by ghidra1** [comment]
Rebased and merged with minor edit

**Comment by WorksButNotTested** [comment]
Excellent. Thanks for the merge. If you're able to look at the related #2066  also, it would be much appreciated.

**Pull request closed without merging**
