### PR TITLE
FIX 599 PDB.EXE Memory leaks due to improper use of COM interfaces

### PR DESCRIPTION
**Pull request by BlueSkeye**
Fix proposal for issue #599 opened by me

Overview :
Created an ITF_RELEASE macro duplicated in each of the three modified files (no code reuse).
Interfaces acquired inside a function are released in this same function. Interfaces provided as parameters left untouched. Comments added whenever something was not obvious (ex : not releasing an interface which is reused later in the same function, ...)

Results :
Using the pdb file named in the issue, memory footprint dropped from 2,6 GBytes to 1,6 GBytes. Processing time down from 110 to 103 seconds.
WARNING : Testing against the sample file requires FIX for #597 to be present.

### CODE REVIEW

**Comment by paulsapps** [comment]
Using CComPtr<T> would be much nicer than manually releasing like this. 👍

**Comment by ghizard** [comment]
@paulsapps I've not used CComPtr.  Are you suggesting, for example:
```
    CComPtr<IDiaSymbol> pSymbol;
    HRESULT hr = pSession->findSymbolByRVA(rva, SymTagPublicSymbol, &pSymbol);
```
and eliminate:
```
		ITF_RELEASE(pSymbol);
```
?

**Comment by chuggafan** [comment]
https://docs.microsoft.com/en-us/cpp/atl/reference/ccomptr-class?view=vs-2019 Seems like he is saying that, CComPtr is, essentially, a shared_ptr for COM classes.

**Comment by paulsapps** [comment]
Yeah that way if there is another exit path or an exception it is still freed

**Comment by ghizard** [comment]
Fixed by #674

**Pull request closed without merging**
