### PR TITLE
Set repeatable comment for function in XML import

### PR DESCRIPTION
**Pull request by saruman9**
XML importer don't import repeatable comment for functions.

### CODE REVIEW

**Comment by astrelsky** [comment]
> XML importer don't import repeatable comment for functions.

It appears to be unset in readStackVariables too.
https://github.com/NationalSecurityAgency/ghidra/blob/07f293cbee89c1698b51d259b712672a7cc2fb08/Ghidra/Features/Base/src/main/java/ghidra/app/util/xml/FunctionsXmlMgr.java#L460-L464

**Comment by saruman9** [comment]
> It appears to be unset in readStackVariables too.

`Variable` can't have repeatable (it's have only one type of comments — regular) type of comments sadly. Also comments for variables can't be viewed in the `Comments` window.

**Comment by astrelsky** [comment]
> > It appears to be unset in readStackVariables too.
> 
> `Variable` can't have repeatable (it's have only one type of comments — regular) type of comments sadly. Also comments for variables can't be viewed in the `Comments` window.

Oh ok I didn't realize that.

**Comment by ryanmkurtz** [comment]
I just tested this and my repeatable function comment did indeed come back in on XML import.

**Comment by saruman9** [comment]
> my repeatable function comment did indeed come back in on XML import

Do you mean _didn't_?

It's because XML exporter of Ghidra don't export repeatable comment:
https://github.com/NationalSecurityAgency/ghidra/blob/decb362234d3ddfead76394b521e5669d2afac05/Ghidra/Features/Base/src/main/java/ghidra/app/util/xml/FunctionsXmlMgr.java#L536-L554

I'm fixing plugin for exporting information from IDA now and tested only with XML from IDA. I'll fix Ghidra XML exporter. I should open new PR or add commits to current?

**Comment by ryanmkurtz** [comment]
Fixing the exporter in this PR would be great.

**Comment by saruman9** [comment]
@ryanmkurtz, I fixed the XML exporter and check it by using Diff View with `Comments` option.

**Comment by saruman9** [comment]
@astrelsky, I'm agree with you and I use in my plugins/scripts `isBlank()`, `isEmpty()` methods, but the construction `comment.length() > 0` is more consistent with others in the file. If Ghidra's developers say me to change this, than I'll change. Also, I think, that commentaries with whitespaces should be exported/imported so that integrity is not broken.

**Comment by astrelsky** [comment]
> @astrelsky, I'm agree with you and I use in my plugins/scripts `isBlank()`, `isEmpty()` methods, but the construction `comment.length() > 0` is more consistent with others in the file. If Ghidra's developers say me to change this, than I'll change. Also, I think, that commentaries with whitespaces should be exported/imported so that integrity is not broken.

Fair enough.  That sort of change can probably be left for their internal review process.

**Pull request closed without merging**
