### PR TITLE
Decompiler: Add C deincrement and increment operator

### PR DESCRIPTION
**Pull request by grant-h**
To improve the readability of decompiled output, extend in place statement emission to include the C increment and decrement operators (++/--).

## Testing
Test data: [tests.zip](https://github.com/NationalSecurityAgency/ghidra/files/5600573/tests.zip)

Commands run (input.txt)
```
restore incdec.xml
load function entry
decompile
print C
q
```

`export SLEIGHHOME=~/ghidra; make decomp_dbg -j && ./decomp_dbg < input.txt`

incdec.xml (BEFORE)
```c
undefined8 entry(void)

{
  uint local_28;
  uint local_24;
  uint local_20;
  uint local_1c;
  uint local_18;
  int local_14;

  __stubs::_memset(&local_28,0,0x18);
  local_28 += 1;
  local_24 -= 1;
  local_20 += 1;
  local_1c -= 1;
  local_18 -= 1;
  local_14 += 1;
  __stubs::_printf("%d %d %d %d %d %d\n",(ulong)local_28,(ulong)local_24,(ulong)local_20,(ulong)local_1c,(ulong)local_18,local_14);
  __stubs::_printf("\n");
  return 0;
}
```
incdec.xml (AFTER)
```c
undefined8 entry(void)

{
  uint local_28;
  uint local_24;
  uint local_20;
  uint local_1c;
  uint local_18;
  int local_14;

  __stubs::_memset(&local_28,0,0x18);
  local_28++;
  local_24--;
  local_20++;
  local_1c--;
  local_18--;
  local_14++;
  __stubs::_printf("%d %d %d %d %d %d\n",(ulong)local_28,(ulong)local_24,(ulong)local_20,(ulong)local_1c,(ulong)local_18,local_14);
  __stubs::_printf("\n");
  return 0;
}
```
incdec_array.xml (BEFORE)
```c
undefined8 entry(void)

{
  uint local_28 [6];

  __stubs::_memset(local_28,0,0x18);
  local_28[0] += 1;
  local_28[1] -= 1;
  local_28[2] += 1;
  local_28[3] -= 1;
  local_28[4] -= 1;
  local_28[5] += 1;
  __stubs::_printf("%d %d %d %d %d %d\n",(ulong)local_28[0],(ulong)local_28[1],(ulong)local_28[2],(ulong)local_28[3],(ulong)local_28[4],local_28[5]);
  __stubs::_printf("\n");
  return 0;
}
```
incdec_array.xml (AFTER)
```c
undefined8 entry(void)

{
  uint local_28 [6];

  __stubs::_memset(local_28,0,0x18);
  local_28[0]++;
  local_28[1]--;
  local_28[2]++;
  local_28[3]--;
  local_28[4]--;
  local_28[5]++;
  __stubs::_printf("%d %d %d %d %d %d\n",(ulong)local_28[0],(ulong)local_28[1],(ulong)local_28[2],(ulong)local_28[3],(ulong)local_28[4],local_28[5]);
  __stubs::_printf("\n");
  return 0;
}
```

I've also tested on larger binaries with great results! Note that the inc/dec operators are not used in expressions, only pure statements, although in idiomatic C it is common for patterns like `while (*a++) { }` or `a[i++]`. To capture these might require more pattern matching.

### CODE REVIEW

**Comment by MrAcartus** [comment]
What about "+=", "-=", "/=", "^="...?
It would be also very good if it all can be toggled on and off.

**Comment by grant-h** [comment]
> What about "+=", "-=", "/=", "^="...?
> It would be also very good if it all can be toggled on and off.

There already is an option for this in the decompiler settings. An option could be added for this as well, but I don't see why X += 1 or X -= 1 would be preferred

**Comment by asmblur** [comment]
I would very much like to see this merged in.  ++ and -- can make things so much less cluttered.

**Comment by grant-h** [comment]
@caheckman mind giving this PR a review?

**Comment by jobermayr** [comment]
This pull request seems to be valid in the form of https://github.com/jobermayr/ghidra-staging/blob/master/2525-Decompiler-Add-C-deincrement-and-increment-oper.patch

**Comment by grant-h** [comment]
I agree, but the PR has no progress after quite some time!

**Comment by jobermayr** [comment]
> I agree, but the PR has no progress after quite some time!

It doesn't mean anything (look at pull request 1892 [20200521 to 20230121])

**Pull request closed without merging**
