### PR TITLE
[decompiler] History navigation by mouse buttons

### PR DESCRIPTION
**Pull request by saruman9**
Works only in Decompiler window (context) and only for my mouse (button number 6 for previous address in the history and button number 7 for next address in the history), but everyone can change buttons in the decompiler's settings. Maybe it's incorrect PR, but it can be used by other users and can be fundament for other changes.

### CODE REVIEW

**Comment by saruman9** [comment]
Relates to #208.

**Comment by Matrix89** [comment]
What's the status on this one?

**Comment by Manouchehri** [comment]
Any progress made on merging this? It's the one missing feature in Ghidra that drives me crazy. =P

**Comment by dragonmacher** [comment]
> Any progress made on merging this? It's the one missing feature in Ghidra that drives me crazy. =P

This change will not be merged, as it is specific to one particular provider.   The real value in this PR is that it helps us gauge interest.    If enough people bump this ticket then we will better be able to decide whether and when we should take this task on.    As it stands now, to correctly add this feature, we would have to add a new tool to option, which is easy, and then examine every use of mouse listeners in the system, which is the tedious part.

**Comment by Washi1337** [comment]
Bump?

Honestly, I am kind of surprised this has not been in Ghidra yet / has not been bumped more. Perhaps it has been drowned in the other issues? I use Ghidra a lot and overall I think the UI is decent hotkeys-wise, but this UX problem can be really annoying. Having to switch from using mouse to keyboard to press alt+left, or move the mouse to mash the back button so many times can really grind gears sometimes.

**Comment by dragonmacher** [comment]
> Is there perhaps a way to help out with this feature if it is a lot of tedious work?

I don't think there is any simple way for the community to contribute on this particular issue.

However, this issue does have a workaround as shown here, albeit clunky: https://github.com/NationalSecurityAgency/ghidra/issues/208

**Comment by hinxx** [comment]
> However, this issue does have a workaround as shown here, albeit clunky: https://github.com/NationalSecurityAgency/ghidra/issues/208

FWIW, #208 solution did not work for me and the mouse I had as it was failing with on the latest Ghidra build (10.1.4):

```
java.lang.NullPointerException
	at MouseToAndFroScript.lambda$createListener$1(MouseToAndFroScript.java:86)
...
```

Got it sorted out with the small change to desired action names:
"Previous in History Buffer" ==> "Previous Location in History"
"Next in History Buffer" ==> "Next Location in History"

Script would also re-add the listener if I re-ran the script. I think I fixed that, too.

For some reason my mouse (logitech G403) did not emit `MOUSE_CLICKED` event on (using Linux) but only `MOUSE_PRESSED` and `MOUSE_RELEASED`; add a small change to workaround that as well.

I can navigate back/forth with the extra mouse button, yay.
Updated script: [MouseToAndFroScript.java.txt](https://github.com/NationalSecurityAgency/ghidra/files/9191530/MouseToAndFroScript.java.txt)

**Comment by ryanmkurtz** [comment]
See #208 discussion for an explanation on why we won't support this.

**Pull request closed without merging**
