### PR TITLE
Copy Jars into lib folder during plugin build automatically

### LINKED ISSUE #2219: Ghidra extension `lib` Dependency Management through Gradle
**Is your feature request related to a problem? Please describe.**
Ghidra extensions are built using Gradle, but the jars for external dependencies need to be placed in the `lib` folder manually.

**Describe the solution you'd like**
A modification to the `GhidraBuild/Skeleton/buildTemplate.gradle` file to include Gradle tasks that automatically copy the JARs into the `lib` folder.

**Describe alternatives you've considered**
Manually copying the dependency JARs over, as is the current workflow.

**Additional context**
I have a patch for this ready (which I wrote for my own Ghidra plugin's build process), but I am gauging interest in adding this feature first.

### PR DESCRIPTION
**Pull request by rlee287**
Resolves #2219.

This is the patch mentioned in that issue, submitted in the form of a pull request for code review.

### CODE REVIEW

**Comment by ryanmkurtz** [comment]
Did you consider using a custom configuration for the extension's dependencies so you don't have to filter out all of Ghidra's dependencies?

**Comment by rlee287** [comment]
I'm not sure what a custom configuration is, but avoiding the need to filter out Ghidra's dependencies sounds like it would be better than what I have in this patch. Could you please elaborate on how this could work?

**Comment by ryanmkurtz** [comment]
Sorry for the delay in getting back to you.  I was playing with this a bit this morning...you can disregard my custom configuration comment...what I was thinking doesn't apply here.

**Review by ryanmkurtz — CHANGES_REQUESTED** [review]
Some suggestions:
1. I think you can move all of your logic into `buildExtension.gradle`.  You'll just have to introduce a new variable in there that represents the Ghidra installation directory (similar to the `ghidraDir` that's already defined).
2. Ideally the user would not have to opt-in to get the copy to happen.  I think it would be ok to just always copy any discovered external jars to the `lib/` dir.
3. We may want some stub code after the "do not modify" section of `buildTemplate.gradle` which directs the user at where to add their dependencies.  Perhaps the maven repository should be added to `buildExtension.gradle` by default

**Comment by ryanmkurtz** [comment]
Btw, I'd be happy to add these changes to your PR to finish it off if you'd like.

**Comment by rlee287** [comment]
I'd prefer that you make these changes to finish the PR, as you have more knowledge and experience working with Ghidra's internals. (This was a solution I created when writing my first Ghidra plugin, so I do not have much experience with Ghidra's internals.)

The "allow edits by maintainers" checkbox is checked, so you should be able to make these changes on the PR, but let me know if you run into issues with this.

**Pull request closed without merging**
