### PR TITLE
Correct supported Windows versions

### PR DESCRIPTION
**Pull request by xiaoyinl**
Windows 7 or 10 -> Windows 7 or later

### CODE REVIEW

**Comment by astrelsky** [comment]
https://www.oracle.com/java/technologies/javase/products-doc-jdk17certconfig.html

I think that will soon be the limiting factor.

**Comment by ryanmkurtz** [comment]
I'll do some testing this week to verify what is still supported under JDK 17.

**Comment by ryanmkurtz** [comment]
The JDK 17 from adoptium.net seemingly runs Ghidra 10.1.5 fine on my Windows 7 VM.

**Comment by ryanmkurtz** [comment]
Note that Amazon Corretto claims support for JDK 17 on Windows 7.  I see no reason to say we don't support it at this time.  I will be happy to change the docs again once the first Windows 7 issue comes in.

**Pull request merged**
