### PR TITLE
Add `mfc71.dll` and `mfc71u.dll` exports.

### PR DESCRIPTION
**Pull request by ColinFinck**
This PR adds `.exports` XML files for the `mfc71.dll` and `mfc71u.dll` libraries. Having them allows Ghidra to translate ordinal imports from applications compiled against MFC 7.1 (from Visual Studio .NET 2003) to class and function names with parameters.
This nicely integrates with the `.exports` files of other MFC DLL versions in that folder.

The files were created like this:
* Insert Visual Studio .NET 2003 Professional CD2, open a Visual Studio Command Prompt and do `cd E:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\atlmfc\lib`
* `dumpbin /exports mfc71.lib > out.txt`
* Open `out.txt` in Notepad++, remove the header and footer lines, so that only lines with ordinals and function names remain.
* Edit -> Line Operations -> Sort Lines Lexicographically Ascending
* Ctrl+H to open Notepad++ Replace dialog, choose "Regular expression", and enter the following:

Find what:
```
 +([0-9]+) +([A-Za-z0-9?$@_]+) (.+)
```
Replace with:
```
    <EXPORT ORDINAL="\1" NAME="\2" PURGE="-1" COMMENT="" />
```

* Add the  `<?xml version="1.0" encoding="UTF-8"?>`, `<LIBRARY NAME="mfc71.dll" PATH="mfc71.dll" DATE="?" VERSION="?">` header and the `</LIBRARY>` footer.

This method can also be applied for any other MFC DLL version (or any other DLL with C++ exports in general), but I only needed version 7.1 for now.
I'm also not aware of any 64-bit version of that DLL, which is why I only added 32-bit exports.

### CODE REVIEW

**Comment by ryanmkurtz** [comment]
We are getting ready to accept this.  I wanted to give you the opportunity to reduce it down to 1 commit (removing the ghidra1 merge commit) so it merges cleanly.  Otherwise, I can just cherry pick your relevant commit, and close this PR manually.

**Comment by ColinFinck** [comment]
Rebased my single commit on top of current master

**Comment by ryanmkurtz** [comment]
Well darn, last night GitHub received our update that moved master to 10.1.  We'd like to get this in 10.0, so if you want to rebase on our `Ghidra_10.0-BETA_build` tag (or commit 75a073bff34842377fd2864d56c9060a7a6595d7 which is our latest 10.0-final commit), for the clean merge, that would be great.  Otherwise I can cherry pick your commit.

**Comment by ryanmkurtz** [comment]
I just noticed that we have pushed the Ghidra_10.0 branch to GitHub, so you could also rebase on that.

**Comment by ColinFinck** [comment]
Next try

**Comment by ryanmkurtz** [comment]
Thanks for your good work, it should make its way up to GitHub sometime next week.

**Comment by ghidra1** [comment]
@ColinFinck , while merging your pull-request I squashed it with our certification record and lost you as the original author.  I apologize for this and appreciate your contribution.  The change has been merged into our Ghidra_10.0 branch for release and should be pushed once we get through testing.

**Comment by ryanmkurtz** [comment]
@ColinFinck, I merged your branch in so you will get credit for your contribution.  The exports files are committed twice, but at least you'll show up in there in the end.

**Pull request closed without merging**
