### PR TITLE
Add functions for handling repeatable comments to the scripting API

### PR DESCRIPTION
**Pull request by snemes**
This is PR adds `setRepeatbleComment`, `getRepeatableComment`, and `getRepeatableCommentAsRendered` to the top level Ghidra scripting environment, for consistency with the other set\*Comment and get\*Comment functions.

Improvement related to question/issue #1245.

### CODE REVIEW

**Comment by dragonmacher** [comment]
This looks good to me.  I can think of no reason why these changes should not be merged it.   I would like a second verification of this though.

**Comment by snemes** [comment]
@dragonmacher can I get your review on this one?

**Comment by ryanmkurtz** [comment]
@snemes, I was about to accept this PR but your merge commit needs to be eliminated.  If you want I can cherry pick the relevant commit, or you could force-push the correction.  The downside to me cherry-picking the commit is that this PR won't appear as "merged."  You will still get credit for being the author though.

**Comment by snemes** [comment]
Is there an easy way to eliminate the merge commit? I tried rebasing, but
didn't work out as I expected and just became an even bigger mess. :)

**Comment by snemes** [comment]
> Is there an easy way to eliminate the merge commit? I tried rebasing, but didn't work out as I expected and just became an even bigger mess. :)

Never mind, I figured it out.

**Comment by ryanmkurtz** [comment]
Looks like your commit author name isn't linked to your GitHub account.  Do you care about that?

**Comment by snemes** [comment]
Thanks for pointing it out, it should be fixed now.

**Pull request merged**
