### PR TITLE
implement function level history navigation

### PR DESCRIPTION
**Pull request by Escapingbug**
implements #454

### CODE REVIEW

**Comment by dragonmacher** [comment]
I think this feature seems like an obviously good feature that we should have included years ago.

I think we probably need some sort of GUI component that makes it clear this functionality exists.  However, what you have done here is an improvement.   I will be adding tests and may be making changes to the code, especially if we feel we need to change the GUI to better integrate this concept.

**Comment by ryanmkurtz** [comment]
@Escapingbug, we had to rebase your branch so this pull-request is showing as closed instead of merged.  Your commit is intact though.  Thanks!

**Comment by mid-kid** [comment]
Sorry to hijack this PR to ask a question, but while I did succeed in setting a comfortable keybinding for this, I'm having trouble finding an option to change the behavior of the toolbar arrows to this. My muscle memory keeps reaching for them, so I'd like to know if there's any way to change it? If there isn't I'll make a proper feature request, but I'm not sure.

**Comment by dragonmacher** [comment]
There is no way to change the behavior of the toolbar arrows.   It would probably not be too difficult to add a tool option to allow the arrows to work in this way.   If you feel this would be helpful to you, please open a new issue for this feature request.

**Pull request closed without merging**
