### PR TITLE
Support for building on ARM

### PR DESCRIPTION
**Pull request by ryanmkurtz**
* Changed the way we name things in the `os/` directories to account for doing builds on non-x86 architectures.
* Added new target platforms for arm64 Linux and macOS (M1)
* Tidied up some Gradle code

Hopefully the community can assist with extensive testing on ARM platforms.

### CODE REVIEW

**Comment by astrelsky** [comment]
Should the `dll` files really be in the repo?

**Comment by ryanmkurtz** [comment]
Yes, they are GPL dependencies which have to be buildable in-place for licensing reasons.

**Comment by astrelsky** [comment]
I understand the intent of this is for ARM support. However, is it possible to create the architecture folder dynamically that would yield the same result while building and at runtime? If someone has a 64 bit linux ppc system (just as an example) is there really a reason why Ghidra shouldn't be able to run?

**Comment by ryanmkurtz** [comment]
The `os` subdirectories are created dynamically from the platforms explicitly defined in `nativeBuildProperties.gradle`.  I think we can continually make improvements to reduce the amount of code that needs to change when we add a new architecture, but I'm not sure how to get around having to define the platforms in `nativeBuildProperties.gradle`.

**Comment by ryanmkurtz** [comment]
@nickg-ca: With these latest changes, are you still only getting an `os/mac_arm_64` decompiler binary when you do a `gradle buildGhidra` on your M1?  When I'm building on my x86 mac, i'm getting x86 binaries put in both `os/mac_arm_64` and `os/mac_x86_64`.

**Comment by ryanmkurtz** [comment]
A quicker test would be to just run `gradle buildNatives_macos_x86_64`.  The task should succeed but not put anything in `os/macos_x86_64` on your M1.

**Comment by nickg-ca** [comment]
@ryanmkurtz When I build with the latest changes in your platforms branch I only get the macos_arm_64 decompile binary. When I run `gradle buildNatives_macos_x86_64` it builds the file in `Ghidra/Features/Decompiler/build/os/macos_x86_64/decompile`, but the file itself is an arm64 executable, not x86_64. I'm not sure if you aim to support cross-compiling, but I thought I'd mention it's not working at the moment in case you do.

**Comment by ryanmkurtz** [comment]
Thanks for retesting.  I just pushed some changes that try to restrict building to the current platform.  I need to research native building more in Gradle....I feel like these changes shouldn't be necessary and that there should be a cleaner way to do it.

**Pull request closed without merging**
