### PR TITLE
New processor for BPF bytecode

### PR DESCRIPTION
**Pull request by Heurs**
This merge request implement processor for BPF bytecode.

### CODE REVIEW

**Review by its0x08 — APPROVED** [review]

**Comment by Nalen98** [comment]
Hi @Heurs!
 Seems there're some similarities with my previous project in 2019 --  [eBPF processor for Ghidra extension](https://github.com/Nalen98/eBPF-for-Ghidra/blob/master/data/languages/eBPF.sinc) (link to eBPF.sinc). Can you comment or give feedback about this? I can assume your pr could be based on this project.

**Comment by Heurs** [comment]
Hi @Nalen98 !
I based myself on your processor indeed to see if I could adapt it. But BPF is too different from eBPF, so I rewrote most of the CPU. Your project is a great job ! I'm even surprised that you didn't submit a MR to propose your eBPF processor ;)

**Comment by Nalen98** [comment]
Thank you, @emteere made a great contribution to the improvement of project and helped me a lot by setting the right tone in the development of processor specifications for Ghidra. Praise to teamwork!

**Comment by GhidorahRex** [comment]
Could you remove the sleighArgs.txt file here?  We normally generate that as part of our build process, and in a different directory. Then do a squash and rebase.

**Comment by GhidorahRex** [comment]
I noticed that the .slaspec is just there to include `endian=little`, but nothing else. There seems to be support for big-endian variants of this. We don't necessarily need to include it currently, but if there's plans to include it later we should consider renaming `BPF.slaspec` to `BPF_le.slaspec`?

(this is the same comment I made regarding the eBPF processor as well).

**Comment by Heurs** [comment]
Thank you for your review. Effectively I have set the endianess to little because CPU is linked to the real processor and those 2 formats exist. I renamed, deleted the file and performed a squash/rebase as asked. Hope everything is ok.

**Pull request merged**
