### PR TITLE
comma separation  

### PR DESCRIPTION
**Pull request by hassan-tahir**

### CODE REVIEW

**Comment by astrelsky** [comment]
No comma before `and`.

**Comment by hassan-tahir** [comment]
Exactly, Forgot to add description. Nevermind!

**Comment by astrelsky** [comment]
> Exactly, Forgot to add description. Nevermind!

Oh my. J completely swapped the addition/deletion in my head while looking at the changes. Please disregard that comment.

**Comment by ryanmkurtz** [comment]
That comma is called an Oxford comma, and it is intentional.

**Comment by hassan-tahir** [comment]
No worries! Thanks for clearance.

**Comment by astrelsky** [comment]
> That comma is called an Oxford comma, and it is intentional.

It's also wrong :rofl:

**Comment by dragonmacher** [comment]
This really points out that we do not use a standard style guide for our documentation.

**Comment by hassan-tahir** [comment]
That doesn't suit your documentation protocols, isn't it?

**Comment by dragonmacher** [comment]
> That doesn't suit your documentation protocols, isn't it?

Since we don't follow a standard, you will get mixed results  :)   I've always been a fan of the Oxford comma, but over the years have let it go as a relic of the past.   But, there is something comforting about the completeness it provides.   Perhaps that is the programmer in me.

**Comment by ryanmkurtz** [comment]
I'm going to keep this closed since we will not be accepting this PR.  Grammar details of this level are out of scope of the Ghidra project.

**Pull request closed without merging**
