### PR TITLE
Save un-maximized/un-iconified bounds in saveToXML()

### PR DESCRIPTION
**Pull request by M-a-r-k**
This addresses Ghidra issue #5879.

### CODE REVIEW

**Comment by dragonmacher** [comment]
I have been trying to get this to work on my system.  This code does not work for me because the value of the rectangle returned by `getBounds()` is the same before and after calling `frame.setExtendedState(JFrame.NORMAL);`.

It seems that to have this work correctly, we would have to track the non-maximized state somehow, which is harder than it appears at face value.

**Comment by M-a-r-k** [comment]
Which platform are you testing on?

I wonder if that on Windows the change is reflected immediately, whereas on e.g. Linux the change may be only reflected when the window manager gets around to it.

**Comment by dragonmacher** [comment]
This is on Linux.  There is clearly some sort of delayed setting and/or event notification happening for me.  I am trying some ideas to get it to work.

**Comment by M-a-r-k** [comment]
I googled "java swing callback maximized" which did seem to give a couple of relevant results:

[Stackoverflow How to detect JFrame window minimize and maximize events?](https://stackoverflow.com/questions/11148950/how-to-detect-jframe-window-minimize-and-maximize-events) 
and
[Oracle page about window listeners](https://docs.oracle.com/javase/tutorial/uiswing/events/windowlistener.html)

Maybe the Windows JDK working "nicely" here is just good luck.

**Comment by dragonmacher** [comment]
I've implemented a workaround that works for me.  Please try it out once it gets merged.

**Comment by M-a-r-k** [comment]
I just built Ghidra to try it out.

This isn't working 100% for me on Windows. Sometimes the non-maximized position is lost.

I tried this:

- Launch Ghidra. Position the window so it occupies e.g. most of the lower right quarter of the screen. Maximize the window.
- Exit Ghidra then launch it again.
- Sometimes I see the window momentarily appear with its previous non-maximized size _and position_, then maximizing. That's correct.
- But other times, the previous non-maximized _position_ seems to be lost. That is, the window momentarily appears at the top left corner of the screen (at its non-maximized size) before maximizing. Thus on un-maximizing, the window is at the top left of the screen, not in the lower-right quarter.

**Comment by dragonmacher** [comment]
This reminds me of a similar problem where sometimes we have windows that are shown at (0,0).   Unfortunately, since I am not seeing the issue, I can't debug it.  This code has changed slightly for a test fix.  It may be worth retrying once that is merged.

**Pull request closed without merging**
