### PR TITLE
Use length == 0 to compare arrays, not ==

### PR DESCRIPTION
**Pull request by GameCubeGBA**
The way it was before could lead to bugs

### CODE REVIEW

**Review by astrelsky — COMMENTED** [review]
I'm not sure what the concern is here. Is it possible for the buf field to have been swapped with a different array that is also empty? If so then I think the appropriate fix would be to check if the length is 0 instead of equality with an empty array.

**Comment by GameCubeGBA** [comment]
Fixed it @astrelsky

**Review by astrelsky — APPROVED** [review]
> Fixed it @astrelsky



> Fixed it @astrelsky

So now that I've had a chance to look at the files on my laptop it appears that `EMPTY` is being used as a sentinel value. This would mean that reference equality would be correct. However, it does seem like it will short-circuit the rest of these two functions more often so I think it is ok.

**Comment by GameCubeGBA** [comment]
Any updates on this?

**Comment by ryanmkurtz** [comment]
I'm a little lost in the history of changes to this PR, but what was wrong with `Arrays.equals()?`  That seems to be the  appropriate replacement for `==` in this case (in terms of readability and safety).

**Comment by GameCubeGBA** [comment]
Arrays.equals() checks to see if they are the same reference, not the same empty contents.

**Pull request closed without merging**
