### PR TITLE
ApplicationUtilities: use XDG on POSIX based platforms

### PR DESCRIPTION
**Pull request by GovanifY**
This PR ensures POSIX based systems are compliant with the XDG base specification ( https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html ).

Up until now caching on Non Windows platforms was also done in the temporary folder of the system, and thus usually had to be recreated from scratch. This makes the behaviour in line with Windows, ensuring the default is $HOME/.cache/Ghidra or $XDG_CACHE_HOME if available.

This fixes https://github.com/NationalSecurityAgency/ghidra/issues/908

### CODE REVIEW

**Comment by hadess** [comment]
Does this also change the default path for scripts and other tidbits? Before this patch, they were still expected to be installed in a subdirectory of the application installation directory, even on Windows, as far as I could tell.

**Comment by GovanifY** [comment]
@hadess This does not change the default path of scripts as this is outside the scope of this PR. This could be implemented after this change is reviewed and accepted.
This effectively only changes the location of $HOME/.ghidra

**Comment by Avamander** [comment]
Is there a blocker to this PR?

**Comment by ryanmkurtz** [comment]
I'll add it to my list.  There's definite value in getting the cached files out of the tmp dir, and if there's a standard place to put it, all the better.  Do you know if macOS uses this?

**Comment by hadess** [comment]
> Do you know if macOS uses this?

macOS uses a different mechanism natively, although you could follow the XDG rules if you don't have any code that knows how to get this info for macOS, it'll still be better than using the Windows paths or a (really) temporary directory.

**Comment by ryanmkurtz** [comment]
Having looked more into XDG and what Windows and macOS do, I think it's more appropriate to fix our locations for config files, cache files, and temp files across the board for all 3 of our platforms, all at the same time.  This PR will use the default XDG locations on macOS, which is just replacing one wrong location with another.  Also, if we get rid of `~/.ghidra` on Linux and macOS, it definitely doesn't make sense to keep it that way for just Windows.  There are also documentation things that need to change if these paths change.

So, I am going to close this PR and use it as a reference for an in-house solution, which can be tracked #908.  I will need to get buy in from some other teammates before proceeding...there might be some other things that depend on these paths that I'm not aware of.  But, it will remain near the top of my list of things to do.

**Comment by ryanmkurtz** [comment]
We also have a feature that will grab the previously used settings when you upgrade to a new version of Ghidra, so we'll need to maintain some backwards compatibility with the old locations.

**Comment by theFr1nge** [comment]
Most programs use the XDG base specification when the directory $XDG_CONFIG_HOME/ghidra exists. If that directory does not exist, they automatically use $HOME/.ghidra. This way backwards compatibility would work fine and people who care about the XDG specification can just create the folder in .config while those who don't can stick to .ghidra. If this is a solution that you would accept, I can create a PR.

**Comment by ryanmkurtz** [comment]
We would never want to fall back to using $HOME/.ghidra, we would simply want to know to look there one time when your Ghidra has been upgraded so we can find the configuration from the previous version.  When these changes go in, that version of Ghidra and all future versions should use XDG...there shouldn't ever be a need for the user to create a directory manually.  

Thanks for the PR offer, but we plan on making these changes internally.  We have all 3 platforms to worry about, and some mundane documentation changes.

**Pull request closed without merging**
