### PR TITLE
Add Dockerfile for easy source builds on GNU/Linux.

### PR DESCRIPTION
**Pull request by nullterminated**

### CODE REVIEW

**Comment by nbulischeck** [comment]
You shouldn't have so many RUN layers. That would explode the size of the docker container.

**Comment by nullterminated** [comment]
>You shouldn't have so many RUN layers. That would explode the size of the docker container.

In my personal case, 3.89GB is fine. What's important to me is running Ghidra on my ARM laptop. I can see file system space being perhaps more important on a CI/CD pipeline. There was an issue about building continuous integration for this project, https://github.com/NationalSecurityAgency/ghidra/issues/333

But it seems continuous integration isn't of great interest to NSA right now. As that is the case, my only other personal concern is getting the Eclipse plugin to build from the installed pde/cdt/pydev plugins, which are also using up space for no good reason :)

I only share this build file to help others in a similar spot, and maybe someone will accept the challenge of getting the Eclipse plugin to build before I have time to come back to it. My feelings won't be hurt if NSA declines this PR. I'll be happy if NSA merely merges https://github.com/NationalSecurityAgency/ghidra/pull/395 so that I don't have to maintain a branch on a fork to stay up to date with my personal builds.

**Comment by nbulischeck** [comment]
Yes, that might be fine for your use case but there really is no sense in not adding a few backslashes to drastically reduce the size of the container. Don't take this as an affront to your ability to write Dockerfiles.

**Comment by nullterminated** [comment]
No offense taken :) You make an astute observation. Just trying to share the context that this file was produced in. Could I make it smaller? Sure. Did I want to spend > 30 minutes per build run on Cinco de Mayo debugging that? I chose to finish up and go enjoy tacos :) My goal that day was accomplished with a working ARM64 build and a dockerfile to prove it.

**Comment by nbulischeck** [comment]
I appreciate the context of your situation, but I recommend only comitting code that is of the best of your ability to public projects.

**Comment by nullterminated** [comment]
You appreciate what I'm working on? Well that's great! It sounds like you're volunteering to finish up this Dockerfile by getting the Eclipse plugin build running. I look forward to seeing it work on multiple CPU architectures :) Be sure to do your best!

**Pull request closed without merging**
