### PR TITLE
copy hasExclusiveAccess pattern into ARM STREX instruction to be the …

### LINKED ISSUE #2010: ARM strex always "resulting" in zero
I have some ARM code that exhibits this

```
                             **************************************************************
                             *                          FUNCTION                          *
                             **************************************************************
                             undefined FUN_1003afc0()
             undefined         r0:1           <RETURN>
                             FUN_1003afc0                                    XREF[8]:     FUN_10003244:10003264(c), 
                                                                                          FUN_1002516c:10025174(c), 
        1003afc0 9f 1f 90 e1     ldrex      r1,[r0]
        1003afc4 01 20 81 e2     add        r2,r1,#0x1
        1003afc8 92 3f 80 e1     strex      r3,r2,[r0]
        1003afcc 00 00 33 e3     teq        r3,#0x0
        1003afd0 fa ff ff 1a     bne        FUN_1003afc0
        1003afd4 02 00 a0 e1     cpy        r0,r2
        1003afd8 1e ff 2f e1     bx         lr
```
which decompiles to:

```
int FUN_1003afc0(int *param_1)

{
  int iVar1;
  
  iVar1 = *param_1;
  *param_1 = iVar1 + 1;
  return iVar1 + 1;
}
```
 looking up LDREX and [STREX ](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dht0008a/ch01s02s01.html) 
they show they are atomic read/writes..

the PCODE for the STREX shows the r3 is always zero, where it seems it should probably have some pcodeop intrinsic

```
                             **************************************************************
                             *                          FUNCTION                          *
                             **************************************************************
                             undefined FUN_1003afc0()
             undefined         r0:1           <RETURN>
                             FUN_1003afc0                                    XREF[8]:     FUN_10003244:10003264(c), 
                                                                                          FUN_1002516c:10025174(c), 
                                                                                          FUN_10035b0c:10035b14(c), 
                                                                                          FUN_10035c78:10035c98(c), 
                                                                                          1003afd0(j), 
                                                                                          thunk_EXT_FUN_1003afc0:50228e98(
                                                                                          50228e9c(*), 509902ac(*)  
        1003afc0 9f 1f 90 e1     ldrex      r1,[r0]
                                                      r1 = LOAD ram(r0)
        1003afc4 01 20 81 e2     add        r2,r1,#0x1
                                                      tmpCY = INT_CARRY r1, 1:4
                                                      tmpOV = INT_SCARRY r1, 1:4
                                                      r2 = INT_ADD r1, 1:4
                                                      tmpNG = INT_SLESS r2, 0:4
                                                      tmpZR = INT_EQUAL r2, 0:4
        1003afc8 92 3f 80 e1     strex      r3,r2,[r0]
                                                      STORE ram(r0), r2
                                                      r3 = COPY 0:4
        1003afcc 00 00 33 e3     teq        r3,#0x0
                                                      $Ubcf0:4 = INT_XOR r3, 0:4
                                                      tmpCY = COPY shift_carry
                                                      tmpOV = COPY OV
                                                      tmpNG = INT_SLESS $Ubcf0, 0:4
                                                      tmpZR = INT_EQUAL $Ubcf0, 0:4
                                                      CY = COPY tmpCY
                                                      ZR = COPY tmpZR
                                                      NG = COPY tmpNG
                                                      OV = COPY tmpOV
        1003afd0 fa ff ff 1a     bne        FUN_1003afc0
                                                      $U340:1 = BOOL_NEGATE ZR
                                                      CBRANCH *[ram]0x1003afc0:4, $U340
        1003afd4 02 00 a0 e1     cpy        r0,r2
                                                      r0 = COPY r2
        1003afd8 1e ff 2f e1     bx         lr
                                                      $U0:4 = INT_AND lr, 1:4
                                                      ISAModeSwitch = INT_NOTEQUAL $U0, 0:4
                                                      TB = COPY ISAModeSwitch
                                                      pc = INT_AND lr, 0xfffffffe:4
                                                      RETURN pc
```
which makes sense:

```
:strex^COND  Rd,Rm,[Rn]    is $(AMODE) &  COND & c2027=0x18 & c0411=0xf9 & Rn & Rd & Rm
{
	build COND;
	*Rn = Rm;
	Rd = 0;
}
```

_Originally posted by @simeonpilgrim in https://github.com/NationalSecurityAgency/ghidra/issues/1661#issuecomment-645822595_

### PR DESCRIPTION
**Pull request by simeonpilgrim**
…same as the THUMB and STREXn instructions, to fix problem I noted in #1661. Fixes #2010

### CODE REVIEW

**Comment by simeonpilgrim** [comment]
With this fix

the decompile has gone from
```
int FUN_1003afc0(int *param_1)

{
  int iVar1;
  
  iVar1 = *param_1;
  *param_1 = iVar1 + 1;
  return iVar1 + 1;
}
```
to 
```
int FUN_1003afc0(int *param_1)
{
  bool bVar1;
  int iVar2;
  
  do {
    iVar2 = *param_1;
    bVar1 = (bool)hasExclusiveAccess(param_1);
  } while (!bVar1);
  *param_1 = iVar2 + 1;
  return iVar2 + 1;
}
```

**Comment by simeonpilgrim** [comment]
my issue that this fixes is moved to #2010

**Comment by astrelsky** [comment]
@simeonpilgrim in order for the issue to automatically be closed you need to use one of the keywords listed [here](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords)

**Comment by simeonpilgrim** [comment]
@astrelsky maybe the workflow is super different to those I am used to elsewhere... so I want the issues case to be closed prior to the PR being merged down? And thus someone will accept the PR if there is a case, and the case is closed?

**Comment by simeonpilgrim** [comment]
fixes #2010

**Comment by astrelsky** [comment]
I think it has to be in the original one

**Comment by simeonpilgrim** [comment]
interesting the issue now shows:

> @simeonpilgrim simeonpilgrim linked a pull request that will close this issue yesterday
> copy hasExclusiveAccess pattern into ARM STREX instruction to be the … #2005

so not sure if how I originally linked it, triggered that (thus it was enough) or how it is now linked by altering the first comment changed the nature of the linking.

**Comment by astrelsky** [comment]
> interesting the issue now shows:
> 
> > @simeonpilgrim simeonpilgrim linked a pull request that will close this issue yesterday
> > copy hasExclusiveAccess pattern into ARM STREX instruction to be the … #2005
> 
> so not sure if how I originally linked it, triggered that (thus it was enough) or how it is now linked by altering the first comment changed the nature of the linking.

It is how it is linked now. It changed after you moved it into the original pull request description/message/comment. I had initially commented that it needs to be in the initial comment but deleted it after I saw you did. Happened to check before and after so I'm certain it was just a reference before and said it will close it after the change.

**Pull request closed without merging**
