### PR TITLE
RISC-V relocations

### PR DESCRIPTION
**Pull request by jnohlgard**
This PR adds implementations for handling some RISC-V relocations that are often found in libraries for bare-metal projects.

### CODE REVIEW

**Comment by thixotropist** [comment]
Are you planning to add implementations for R_RISVC_{RELAX,ADD32,SUB32, 32_PCREL,SET6,SET8,SUB6,SUB8}?  I'm seeing these generated by the riscv/riscv-gnu-toolchain .

**Comment by jnohlgard** [comment]
ADD,SUB seem to be implemented already in the code, although the warning is still in there. RELAX does not really make sense to do anything with when reverse engineering an object file, it is used to reduce code size in the final linked binary.
I found a mistake in the HI20 computation when the companion LO20 relocation is negative. This is fixed in this PR now.

**Comment by thixotropist** [comment]
Ghidra decompiler output looks good with the revised commit.  I compared 10.1.1 with 10.2 DEV after merging your fork and rebasing and rebuilding.  Test cases included riscv64 debug and optimized object files compiled with g++ 11.1.0.

**Comment by mumbel** [comment]
I think I originally only implemented the ones that I had in my sample executable and didn't really make an attempt to go find more or look at shared objects which might have others.   Made some guesses on a few that made sense, but think I accidentally left the todo comment as you noticed.

Did come across more in a project, I'm surprised an MR was never opened, but it was developed right as ghidra was releasing RISC-V support and most people AFAIK were just using my out of tree module instead of building master.  Might be helpful https://github.com/micahswitzer/ghidra_riscv

**Comment by micahswitzer** [comment]
> @thixotropist 
Are you planning to add implementations for R_RISVC_{RELAX,ADD32,SUB32, 32_PCREL,SET6,SET8,SUB6,SUB8}? I'm seeing these generated by the riscv/riscv-gnu-toolchain .

As @jnohlgard already said, `RELAX` is unnecessary for proper decompilation (its purpose is to tell the linker that it can save space if it wants to) and `ADD32`, `SUB32`, and `SUB8` work fine from my testing (I removed the warnings in my fork of mumbel's module).

`SET6`, `SET8`, and `SUB6` were all implemented by me (although apparently I never was able to test them).

> @mumbel 
I'm surprised an MR was never opened

Yeah I got lazy and never put in the effort. Maybe I'll open one for the ones this MR doesn't address.

@jnohlgard I'm not sure what you're testing with, but the files I was looking at are here if you want more "real world" samples:
https://github.com/pine64/bl602-re/blob/master/blobs/libatcmd.a
https://github.com/pine64/bl602-re/blob/master/blobs/libbl602_wifi.a
https://github.com/pine64/bl602-re/blob/master/blobs/libblecontroller.a

**Comment by jnohlgard** [comment]
Here's one archive that I have used as a test subject for the changes in this PR: https://github.com/bouffalolab/bl_mcu_sdk/blob/master/components/mac154/lmac154/lib/liblmac154.a

**Comment by thixotropist** [comment]
If you need a sample riscv-64 binary that uses the unsupported relocations, try extracting `igc.ko` from [Fedora 37 for Riscv](https://dl03.fedoraproject.org/pub/alt/risc-v/disk_images/Fedora-Developer-37-20221130.n.0.SiFive.Unmatched/Fedora-Developer-37-20221130.n.0-mmc.raw.img.xz)

The import log shows a problem importing symbols and several types of relocation symbols used in linking kernel modules to base kernel symbols:

```text
Error creating symbol: .L112 - Symbol name contains invalid characters: .L112
Error creating symbol: .L01 - Symbol name contains invalid characters: .L01
Error creating symbol: .L135 - Symbol name contains invalid characters: .L135
Error creating symbol: .L02 - Symbol name contains invalid characters: .L02
...
Elf Relocation Warning: Type = R_RISCV_RVC_BRANCH at 00100e62, Symbol = .L1: TODO, needs support 
...
Elf Relocation Warning: Type = R_RISCV_BRANCH at 00100eee, Symbol = .L19: TODO, needs support 
...
Elf Relocation Warning: Type = R_RISCV_CALL at 00100f6a, Symbol = memcpy: TODO, needs support 
...
Elf Relocation Warning: Type = R_RISCV_PCREL_HI20 at 0010120c, Symbol = .LC0: TODO, needs support 
Elf Relocation Warning: Type = R_RISCV_PCREL_LO12_I at 00101210, Symbol = .L0: TODO, needs support 
```

Running ghidra in foreground shows two errors with this import:

```
ERROR Failed to process GOT at 00100028: Insufficent memory at address 00100028
(length: 8 bytes) (ElfDefaultGotPltMarkup) ghidra.program.model.util.CodeUnitInsertionException: Insufficent memory at address 00100028 (length: 8 bytes)
	at ghidra.program.database.code.CodeManager.checkValidAddressRange(CodeManager.java:1868)
ERROR Failed to process GOT at 001003c1: Insufficent memory at address 001003c1 (length: 8 bytes) (ElfDefaultGotPltMarkup) ghidra.program.model.util.CodeUnitInsertionException: Insufficent memory at address 001003c1 (length: 8 bytes)

```

The error addresses match the beginning of the .got and .plt segments

`readelf igc.ko` doesn't show any problems with symbols like .L1

The equivalent x86_64 kernel load module loads cleanly, with the kernel symbols nicely linked.

Tested with ghidra_10.3.2 and ghidra_10.4_DEV

**Comment by ghidra1** [comment]
@thixotropist I will look into this while reviewing and handling this merge request

**Comment by thixotropist** [comment]
Sounds good.  Keep an eye out for riscv's use of signed addition - the high
20 bit value may need to be incremented when adding the low order 12 bits
with signed arithmetic.

**Comment by ghidra1** [comment]
Have all interested parties reviewed the relocations implemented by this PR?  I noticed that a few differ from how @micahswitzer had implemented in his fork ([](https://github.com/micahswitzer/ghidra_riscv)) (i.e. `R_RISCV_CALL`, `R_RISCV_LO12_I`, `R_RISCV_LO12_S`).

@micahswitzer would you mind if I lifted your implementations for `R_RISCV_SUB6`, `R_RISCV_SET6`, and `R_RISCV_SET8`?

**Comment by thixotropist** [comment]
I haven't submitted a formal review. The PR's implementation of RISCV_CALL
probably needs correction for signed addition.  Please feel free to lift
anything you like from https://github.com/thixotropist/ghidra's
riscv_relocation branch, and test with examples big enough to require
offsets of 0x800 or more.

If possible, can you comment on what test inputs your team wants to use for
RISCV binaries?  64 bit user space processes look pretty good, PIC object
files and kernel load modules get some attention in my fork.  My code for
R_RISCV_PCREL_LO12_I is ugly - with relocations referring to other
relocations at addresses that hold yet other relocation codes.

Who knows what kind of relocations are common in object files with link
time optimization.

**Comment by ghidra1** [comment]
@thixotropist Could you review/examine the `R_RISCV_CALL`, `R_RISCV_LO12_I`, `R_RISCV_LO12_S` in this PR.  The implementations differ from your changes.

**Comment by thixotropist** [comment]
I believe that the PR implementation of R_RISCV_CALL needs to be corrected to allow for signed immediate addition in the jalr statement.  See https://riscv.org/wp-content/uploads/2017/05/riscv-spec-v2.2.pdf:

    The indirect jump instruction JALR (jump and link register) uses the I-type encoding. The target address is obtained by adding the 12-bit signed I-immediate to the register rs1, then setting the least-significant bit of the result to zero.

The fix is to copy PR code from R_RISCV_HI20, adding 0x800 before masking.

The handler should treat R_RISCV_CALL_PLT and  R_RISCV_CALL the same, so I stack these cases in my code.

The PR's implementation of R_RISCV_LO12_I looks correct.  I don't have a test case for R_RISCV_LO12_S, so I can't say one way or the other.

My code refactors some of the high-20 and lo-12 calculations into static functions, so that goes beyond the scope of this PR.

I could work up some riscv elf import/relocation test cases and maybe a framework for regression testing if that helps.

**Comment by micahswitzer** [comment]
> Have all interested parties reviewed the relocations implemented by this PR? I noticed that a few differ from how @micahswitzer had implemented in his fork () (i.e. `R_RISCV_CALL`, `R_RISCV_LO12_I`, `R_RISCV_LO12_S`).

After reviewing my implementations of `R_RISCV_LO12_I` and `R_RISCV_LO12_S`, I believe that I accidentally got those mixed up with the PIC versions.

> @micahswitzer would you mind if I lifted your implementations for `R_RISCV_SUB6`, `R_RISCV_SET6`, and `R_RISCV_SET8`?

Yeah that's totally fine. I'd appreciate contributor credit, but that's not necessary.

**Comment by ghidra1** [comment]
@micahswitzer I can do as a separate commit with you as author.  I will be re-creating commits in any case due to rebase and adding additional changes myself in another commit.

**Comment by ghidra1** [comment]
@thixotropist In the process of integrating your changes with this PR I was examing your `getSymbolValueIndirect` method implementation.  Is there any guarentee that the related `HI20` relocation was processed before the `R_RISCV_PCREL_LO12_I` relocation?  If not the DB-stored relocation table will not yet contain the required relocation.  It may be preferable to search the raw relocation tables accessed via the `ElfHeader`.  Do you have any examples which demonstrate this applied relocation?

**Comment by ghidra1** [comment]
I will be pushing relocation changes for 10.4, however I did not have time to look into the symbol naming issue.  I changed the way the HI20 relocation lookup occurs, although I too was unable to verify at this point.  If anyone can point me to, or supply, a binary sample with `R_RISCV_PCREL_LO12_I` or `R_RISCV_PCREL_LO12_S` relocations I would appreciate it.

@thixotropist Re: "more link- and load-time optimizations through relocation codes" - I don't know the answer to this.

**Pull request closed without merging**
