### PR TITLE
Mips special 1f

### PR DESCRIPTION
**Pull request by mumbel**
Came across a binary that needed a few OCTEON/DSP instructions and features.

Noticed that several instructions, have a potentially incorrect prime bitpattern:

cache, cachee, lbe, lbue, lhe, lhue, lle, lwe, prefe, sbe, sce, she, swe, lwle, lwre, lwle, lwre, swle, swre, swle, swre, scxe

### CODE REVIEW

**Comment by emteere** [comment]
Thanks for the pull request. Was just about to look at this when I saw your changes.
I like you refactored the decimal into the hex format, but it does make it hard to review actual changes.
I have to hover over each one...

Looks good.  Not sure how someone missed those special3 0x1F patterns.

**Comment by mumbel** [comment]
sorry about that.  The ws and dec->hex did make this commit significantly larger and uglier than it needed to be, but hopefully the end result is easier to manage.  thanks for taking a look.  let me know if you have questions/issues with the new octeon instructions  i was hoping to get included or the changes to acc lo/hi?  I can break down the pull request into multiple if you'd like so the bugfix is separated.

**Comment by ryanmkurtz** [comment]
I'm getting ready to merge this in but the branch seems to be in a weird state, with 2 different commits/committers.  Would you mind trying to squash it down @mumbel?  Thanks!

**Comment by mumbel** [comment]
dang, im bad at git,  I had a bad email originally and tried to amend past commits to the noreply, and guess I messed it up pretty badly.  did this fix it?

**Comment by ryanmkurtz** [comment]
No, it looks like more commits got added.  There's a 3rd unique email address in there now.  Are you using git from the command line or a GUI tool?

**Comment by mumbel** [comment]
just the standard linux git cli client...   if that didnt fix it... i give up
It may just be easier to close an reopen with a new branch at this point D:

**Comment by ryanmkurtz** [comment]
Something that might also be causing problems is it looks like you are merging our repo back into your fork...that will create some additional commits on our end.  I think you just want to fork our repo and work from that fork point.  You are right, it might be easier to just recreate it.  I could also just force it in for you but you might not get proper credit for the commit on Github.

**Comment by mumbel** [comment]
Okay, sounds like I should probably close all my current PR maybe, correct email and remove the merges to my master and just fork as you stated, sorry new to git (I really dont care about credit, except on the tricore if that gets merged, which has the same email issue as here, but at least forked correctly)

**Comment by ryanmkurtz** [comment]
Let me get someone else here to look at them before you do that...maybe they'll know something I don't.  I don't want you to have to do unnecessary work.

**Comment by ryanmkurtz** [comment]
What does Github tell you your private commit email address is in your settings?  Is it mumbel@users.noreply or ###-mumbel@users.noreply?

**Comment by mumbel** [comment]
The ###, I just hadn't ever noticed the ### in any other persons noreply, so I chopped it off

**Comment by ryanmkurtz** [comment]
I was also recently wondering about that and I found [this](https://help.github.com/en/articles/setting-your-commit-email-address):

> Note: If you created your GitHub account after July 18, 2017, your GitHub-provided no-reply email address is a seven-digit ID number and your username in the form of ID+username@users.noreply.github.com. If you created your GitHub account prior to July 18, 2017, your GitHub-provided no-reply email address is your username in the form of username@users.noreply.github.com. You can get an ID-based GitHub-provided no-reply email address by selecting (or deselecting and reselecting) Keep my email address private in your email settings.

**Comment by mumbel** [comment]
Okay. I think after work I'll correct my client to ### and close/fix/reopen PRs with clean forks/commit If you wanted to get this added today, I'm really okay with you forcing with your acct as author/committer

**Comment by ryanmkurtz** [comment]
So for this one I just cherry picked your commit with the correct email address into our master branch.  Since that creates a new commit this branch didn't get properly marked as merged, but you got credit for the commit.  I would make sure that your email address in your .gitconfig file is the one with the numbers in it moving forward.

For your other pull-requests, if their branches have commits that say things like "Merge pull request #10 from NationalSecurityAgency/master", that's bad...we won't be able to merge that into our master branch easily and it won't integrate very well with Github's pull request system.  

In general, you want your git history to look exactly like our master branch's git history (from the point in time you branched), with only your commits on top in a straight line.  If you submit a branch that looks like that as a pull-request, everything should go smoothly.

Thanks for all of your contributions!

**Pull request closed without merging**
