### PR TITLE
Change “Mac OS” to “macOS”

### PR DESCRIPTION
**Pull request by NonCreature0714**
Edited to "Mac OS" to "macOS" per Apple's official name. Added contributors file based on my interpretation of the guidelines.

### CODE REVIEW

**Comment by Ristovski** [comment]
Please squash your commits as stated in [CONTRIBUTING.md](CONTRIBUTING.md):

> Before submission, please squash your commits to using a message that starts with the issue number and a description of the changes.

Having 4 commits for a single change is sub-par.

I would also advise to change the PR title to reflect the changes in a more clear manner.

**Comment by wedemmoez** [comment]
This is the weakest way to become a contributor that I have ever seen.

**Comment by ctubbsii** [comment]
Commits can be squashed when merged, so it's not a big deal if they're not squashed before hand.

**Comment by Escapingbug** [comment]
When will people know that contributor is just a title.. What really matters is you work.

**Comment by AnthonyCamper** [comment]
Thank you for this patch! Really helpful

**Comment by NonCreature0714** [comment]
> This is the weakest way to become a contributor that I have ever seen.

I actually thought this was pretty funny coming from a guy with 12 commits in the last year.

**Comment by NonCreature0714** [comment]
I read through the documents looking for grammar and spelling errors, without objecting my own opinion or interpretation of word choice or phrasing. This is the one mistake I found. 

It’s small, but correct. If I found something else, I would have corrected them as well.

Perhaps it is a low hanging fruit.

Or perhaps no one else noticed or cared.

I noticed. I cared. So I made the change.

**Comment by NonCreature0714** [comment]
I also wonder why this has received so much negative criticism, because I don’t see it as much different than #42

**Comment by ctubbsii** [comment]
@NonCreature0714 Small improvements are appreciated, too, so I wouldn't worry about the criticism. I think people are just expressing their amusement at how small a PR can be. I wouldn't take the criticism too seriously.

As for the proposed change, I wasn't able to find any specific press release or other announcement from Apple regarding a preference (if you have a link, it would satisfy my personal curiosity). However, from a brief web search, it does appear that they started using the "macOS" trademark instead of "Mac OS X" as of version 10.12 in 2016. I think people will know what is meant either way, but clearly the "macOS" one is more current, so it probably does make sense to use that.

The real reason this hasn't been merged in yet, whereas others have, is not the criticism... rather, it is that your PR prompted me to have a few DCO-related questions, and I paused my helping merge PRs until I can get those answered. With any luck, I'll get clarification quickly, and I, or somebody else, will merge in your proposed change in short order. I ask for your patience. :smile:

**Comment by pythlang** [comment]
He’s actually correct, although I was previously unaware; for example, when releasing apps on the App Store there are specific guidelines for marketing and term usage. I can try to find them again for you.

**Comment by NonCreature0714** [comment]
At the [WWDC 16 Keynote](
https://developer.apple.com/wwdc16/101), at about the 36 minute mark, Craig Federighi announced that OSX would be renamed macOS.

**Comment by nsadeveloper789** [comment]
Thank you for this fix. I often start typing macOS out and wonder what's proper. Now I know. We resolved the DCO issue for now by switching to a simpler inbound=outbound model. Thus, I squashed out your changes to the contributors.md file and merged your actual fix in. I left the signed-off-by line in the commit, since it doesn't hurt.

**Comment by ctubbsii** [comment]
@NonCreature0714  Your commit got merged as ce0b87f2b14e8efd4788b9d804ce09d3c1b4bc59

**Comment by NonCreature0714** [comment]
@ctubbsii That suggestion helped, thank you :)

**Pull request closed without merging**
